PROGRAM GETEFDC
! ** PURPOSE:
! ** TO EXTRACT BINARY OUPUT OF EFDC TO ASCII DATA FILES FOR
! 1. TIME SERIES:
!    AT SOME LOCATIONS INDICATED BY (I,J) OR (X,Y) OF LAYER K>0
!    IF K=0 THEN DATA FOR DEPTH-AVERAGE IS EXPORTED
! 2. TECPLOT DATA
! 3. VERTICAL PROFILES
! 3. ARRAYS OF DATA

! ** INPUTS:
! GETEFDC.INP : THIS FILE MUST BE EDITED FOR EACH PROJECT
! EFDC.INP
! LXLY.INP
! DXDY.INP
! CELL.INP
! CORNERS.INP
! MAPPGNS.INP
! ASER.INP
! AND ALL OUTPUT OF EFDC

! ** OUPUT:
! ** OUTPUT OF GETEFDC IS STORED IN RESULT FOLDER
!
! ** AUTHOR: DH CHUNG
! ** UPDATE: 2015-06-12
! ** NDLuan
! ** UPDATE: 2018-12-04

USE GLOBALVARS
USE EFDCPROMOD
USE GETEEOUTMOD
USE GETHFREQOUT
USE INFOMOD
USE XYIJCONV
USE IFPORT

IMPLICIT NONE
INTEGER(4)    ::N,I,J,IS,L,IOS,NS
INTEGER(4)    ::STATUS,INDEX,TECOPT,RSTAT
CHARACTER(200)::BUFFER, GETEFDCINP
LOGICAL(4)    ::RES,OUTS

!*** READ GETEFDC.INP FILE DETERMINED BY USER
PRINT*,'************************************************************************'
PRINT*,'*** GetEFDC IS DEVELOPED BY DYNAMIC SOLUTIONS-INTERNATIONAL IN HANOI ***'
PRINT*,'*** IT IS USED TO:                                                   ***'
PRINT*,'***   EXTRACT EFDC OUTPUT FILES (BINARY) FOR LAYER/TIMESERIES DATA   ***'
PRINT*,'*** THE OPTIONS FOR EXTRACTION DATA IS IN THE FILE GETEFDC.INP       ***'
PRINT*,'*** THEREFORE PLEASE EDIT THIS FILE ACCORDING TO YOUR NEED FIRST     ***'
PRINT*,'*** THEN RUN THIS PROGRAM BY ENTERING THE FOLLOWING COMMAND:         ***'
PRINT*,'*** >       GETEFDC.EXE GETEFDC.INP                                  ***'
PRINT*,'************************************************************************'
PRINT*,' '

CALL GETARG(1,BUFFER,STATUS)
IF (STATUS==-1) STOP 'GETARG ERROR: GETEFDC.INP IS NOT FOUND!'
GETEFDCINP = BUFFER(1:STATUS)
PRINT*,'*** BUFFER: '//trim(GETEFDCINP)
PRINT*,' '
PRINT*,'************************************************************************'
PRINT*,'*** READING GETEFDC.INP FILE'
OPEN(UINP,FILE=GETEFDCINP)
CALL ERRMES(UINP,GETEFDCINP)

CALL SKIPCOM(UINP, '*')
READ(UINP,'(A)') EFDCFILE
CALL REMOVTAB(EFDCFILE)
CALL ROOTFOLDER_C(EFDCFILE,INPFOLDER)

LXLYFILE = trim(INPFOLDER)//'lxly.inp'
DXDYFILE = trim(INPFOLDER)//'dxdy.inp'
CELLFILE = trim(INPFOLDER)//'cell.inp'
CORNFILE = trim(INPFOLDER)//'corners.inp'
MAPNSFILE = trim(INPFOLDER)//'mappgns.inp'
MAPEWFILE = trim(INPFOLDER)//'mappgew.inp'

ASERFILE = trim(INPFOLDER)//'aser.inp'
SETSFILE  = trim(INPFOLDER)//'subset.inp'
SGZFILE   = trim(INPFOLDER)//'sgzlayer.inp'
DRIFILE   = trim(INPFOLDER)//'drifter.inp'
OUTFOLDER = TRIM(INPFOLDER)//'#output\'

WSFILEI = trim(OUTFOLDER)//'EE_WS.OUT'
VEFILEI = trim(OUTFOLDER)//'EE_VEL.OUT'
HYFILEI = trim(OUTFOLDER)//'EE_HYD.OUT'
WCFILEI = trim(OUTFOLDER)//'EE_WC.OUT'
WQFILEI = trim(OUTFOLDER)//'EE_WQ.OUT'
LPTFILE = trim(OUTFOLDER)//'EE_DRIFTER.OUT'
BCFILEI = trim(OUTFOLDER)//'EE_BC.OUT'
BEFILEI = trim(OUTFOLDER)//'EE_BED.OUT'
TUFILEI = trim(OUTFOLDER)//'EE_TUR.OUT'

RES = CHANGEDIRQQ(INPFOLDER)

CALL SKIPCOM(UINP, '*')
READ(UINP,*) LAYK, JULTIME, NLOC, ROT, INDEX, VPROFILE,TECOPT,ZOPT,NDRIFTER
IF (VPROFILE>=1) THEN
  VPROFCHK =.TRUE.
ELSE
  VPROFCHK =.FALSE.
ENDIF
IF(TECOPT==1) THEN
  TECCHKL=.TRUE.
ELSE
  TECCHKL=.FALSE.
ENDIF

ALLOCATE(ICEL(NLOC),JCEL(NLOC))
ALLOCATE(XCEL(NLOC),YCEL(NLOC))
ALLOCATE(ZINT(NLOC),ZSIG(NLOC))

CALL SKIPCOM(UINP, '*')
IF(INDEX==1) THEN
  DO N=1,NLOC
    READ(UINP,*) ICEL(N),JCEL(N),ZINT(N)
  ENDDO
ELSE
  DO N=1,NLOC
    READ(UINP,*) XCEL(N),YCEL(N),ZINT(N)
  ENDDO
ENDIF


CLOSE(UINP)

! ** START
PRINT*,'*** READING THE EFDC INPUT FILES: '
CALL EFDCPRO

IF (LAYK==-1.AND.HFREOUT==1) THEN
  PRINT*,'*** READING THE HIGH FREQ. OUTPUT FILES: '
  NGROUP = 0        !All groups
  NPOINT = 0        !All points
  RES = MAKEDIRQQ('#output\HFREDAT')
  CALL AREA_CENTRD  !CAL XCOR,YCOR & AREA
  CALL GETHFREQ
ELSEIF (LAYK==-3) THEN
  PRINT*,'*** READING THE TMP FILE: '
  RES = MAKEDIRQQ('#output\RESULT')
  CALL AREA_CENTRD  !CAL XCOR,YCOR & AREA
  CALL READ_TMP
  STOP
ELSE
  RES = MAKEDIRQQ('#output\RESULT')
  IF (.NOT.RES) THEN       
    RES = GETLASTERRORQQ( )  
    IF (RES==ERR$NOENT) THEN
      PRINT*,'THE PATH FOR RESULT IS NOT FOUND'
      PAUSE(1)
      STOP
    ELSEIF (RES==ERR$ACCES) THEN
      PRINT*,'CANNOT CREATE THE FOLDER: PERMISSION DENIED!'
      PAUSE(1)
      STOP
    ENDIF
  ENDIF
   
  ! ** LABELS FOR OUTPUT FILENAMES:
  WRITE(SSTR1,'(I8)') NINT(JULTIME)
  WRITE(SSTR2,'(I2)') LAYK
  WRITE(SSTR3,'(I2)') NLOC
  SSTR1 = ADJUSTL(SSTR1)
  SSTR2 = ADJUSTL(SSTR2)
  SSTR3 = ADJUSTL(SSTR3)
  
  DO N=1,NTSWQVM
    UOUTI(N)  = 200+N
    UCVPRF(N) = 300+N
  ENDDO
  UOUTI(50:100) = (/(500+N,N=50,100)/)
  
  ! ** OUTPUT FILES FOR THE SELECTED LAYER:
  WSFILEO = '#output\RESULT\DEP_TSK_'//TRIM(SSTR2)//'_DOM.DAT'
  TSWSF   = '#output\RESULT\DEP_TSK_'//TRIM(SSTR2)//'_CEL.DAT'
  TSICF   = '#output\RESULT\ICE_TSK_'//TRIM(SSTR2)//'_CEL.DAT'
  
  IF (LAYK/=0) THEN
    VEFILEO = '#output\RESULT\VEL_TSK_'//TRIM(SSTR2)//'_DOM.DAT'
    TSVEF   = '#output\RESULT\VEL_TSK_'//TRIM(SSTR2)//'_CEL.DAT'
    TSBCF     = '#output\RESULT\QSM_TSK_'//TRIM(SSTR2)//'_CEL.DAT'
  ELSEIF(LAYK==0) THEN  
    VEFILEO = '#output\RESULT\VEL_TSK_0_DOM.DAT'
    TSVEF   = '#output\RESULT\VEL_TSK_0_CEL.DAT'
  ENDIF

  IF (VPROFCHK) THEN
    VELPROFILE = '#output\RESULT\VEL_PROF.DAT'
    SALPROFILE = '#output\RESULT\SAL_PROF.DAT'
    TEMPROFILE = '#output\RESULT\TEM_PROF.DAT'
    DYEPROFILE = '#output\RESULT\DYE_PROF.DAT'
    TOXPROFILE = '#output\RESULT\TOX_PROF.DAT'
    SEDPROFILE = '#output\RESULT\SED_PROF.DAT'
    SNDPROFILE = '#output\RESULT\SND_PROF.DAT'
    CHCTSFPROF = '#output\RESULT\CHC_PROF.DAT'
    CHDTSFPROF = '#output\RESULT\CHD_PROF.DAT'
    CHGTSFPROF = '#output\RESULT\CHG_PROF.DAT'
    ROCTSFPROF = '#output\RESULT\ROC_PROF.DAT'
    LOCTSFPROF = '#output\RESULT\LOC_PROF.DAT'
    DOCTSFPROF = '#output\RESULT\DOC_PROF.DAT'
    ROPTSFPROF = '#output\RESULT\ROP_PROF.DAT'
    LOPTSFPROF = '#output\RESULT\LOP_PROF.DAT'
    DOPTSFPROF = '#output\RESULT\DOP_PROF.DAT'
    P4DTSFPROF = '#output\RESULT\P4D_PROF.DAT'
    RONTSFPROF = '#output\RESULT\RON_PROF.DAT'
    LONTSFPROF = '#output\RESULT\LON_PROF.DAT'
    DONTSFPROF = '#output\RESULT\DON_PROF.DAT'
    NHXTSFPROF = '#output\RESULT\NHX_PROF.DAT'
    NOXTSFPROF = '#output\RESULT\NOX_PROF.DAT'
    SUUTSFPROF = '#output\RESULT\SUU_PROF.DAT'
    SAATSFPROF = '#output\RESULT\SAA_PROF.DAT'
    CODTSFPROF = '#output\RESULT\COD_PROF.DAT'
    DOXTSFPROF = '#output\RESULT\DOX_PROF.DAT'
    TAMTSFPROF = '#output\RESULT\TAM_PROF.DAT'
    FCBTSFPROF = '#output\RESULT\FCB_PROF.DAT'
  ENDIF

  IF (JULTIME<=0) THEN
    ALLSNAP=1     !OUTPUT ALL SNAPSHOTS FOR TECPLOT
  ELSE
    ALLSNAP=0
  ENDIF

  ! ** READ EFDC INPUT FILES AND DETERMINE THE MODEL GRID PARAMETERS
  IF(INDEX==0) THEN
    CALL XY2IJ
    RSTAT = 0
  ELSE
    CALL AREA_CENTRD(1)
    RSTAT = 1
  ENDIF

  DO N=1,NLOC
    L= LIJ(ICEL(N),JCEL(N))
    IF (L<=1) THEN
      PRINT '(10x,A7,I2,A22)','CELL # ',N,' IS OUTSIDE THE DOMAIN'
      STOP
    ENDIF
  ENDDO

  !*** READ WS AND VELOCITY AND WRITE SELECTED DATA 
  PRINT*,'*** READING EE_WS.OUT AND EXPORTING DATA '
  CALL GETEE_WS
  IF (LAYK > 0) CALL GETEE_BC
  PRINT*,'*** READING EE_VEL.OUT AND EXPORTING DATA '
  IF (LAYK/=-1) CALL GETEE_VE
  
  PRINT*,'*** READING EE_TUR.OUT AND EXPORTING DATA '
  CALL GETEE_TU
  
  !*** READ EE_WC.OUT AND WRITE SELECTED DATA
  IF(ANY(ISTRAN(1:7)==1)) THEN  
    PRINT*,'*** READING EE_WC.OUT AND EXPORTING DATA '
    IF (LAYK/=-1) CALL GETEE_WC
  ENDIF
  
  IF( ISBEXP >= 1 .AND. KB > 1 )THEN
    IF( ISTRAN(6) >= 1 .OR. ISTRAN(7) >= 1 )THEN
      PRINT*,'*** READING EE_BED.OUT AND EXPORTING DATA '
      CALL BEDOUT
    ENDIF
  ENDIF
  
  !*** READ EE_WQ.OUT AND WRITE SELECTED DATA
  IF(ISTRAN(8)==1) THEN
    PRINT*,'*** READING EE_WQ.OUT AND EXPORTING DATA '
    IF (LAYK/=-1) CALL GETEE_WQ
  ENDIF

  !*** READ EE_DRIFTER.OUT & WRITE SELECTED DRIFTERS
  IF(ISPD >= 2) THEN
    PRINT*,'*** READING EE_DRIFTER.OUT AND EXPORTING DATA '
    IF(RSTAT==0) CALL AREA_CENTRD(1)
    CALL GETLPT
  ENDIF
  
  
ENDIF
PRINT*,' '
PRINT*,'*** OK ./'
PRINT*,'************************************************************************'
PAUSE
END PROGRAM
