MODULE GETHFREQOUT
! ** TO GET HIGH FREQUENCY OUTPUT FOR TIMESERIES
! ** NGROUP==0 FOR ALL GROUPS
! ** NPOINT==0 FOR ALL POINTS
! ** AUTHOR: DH CHUNG

USE GLOBALVARS
USE EFDCPROMOD,ONLY:FREEMEM
USE INFOMOD
USE IFPORT
USE TECMOD
USE XYIJCONV

IMPLICIT NONE

CONTAINS
SUBROUTINE GETHFREQ
INTEGER(4)    ::N,I,IS,nc_id,L,LS,ISO
INTEGER(4)    ::STATUS,ENDR,NCAL,NS
CHARACTER(200)::BUFFER, NCFILE*50,STR*5,MESS,NSTR*5
LOGICAL(4)    ::RES

DO N=1,NTSWQVM
  UOUTI(N)  = 200+N
  UCVPRF(N) = 300+N
ENDDO

!*** READ EFDC INPUT FILES AND DETERMINE THE MODEL GRID PARAMETERS

OPEN(1,FILE=SETSFILE,action='read')
CALL SKIPCOM(1,'*')
READ(1,*,IOSTAT=ISO) NSUBSET
IF(ISO>0) STOP 'SUBSET.INP: READING ERROR!'
ALLOCATE(HFREGRP(NSUBSET))
ALLOCATE(IJHFRE(NSUBSET),HFREDAYBG(NSUBSET),HFREDAYEN(NSUBSET))
ALLOCATE(HFREDUR(NSUBSET),HFREDAY(NSUBSET),HFREMIN(NSUBSET),NPNT(NSUBSET))
DO NS=1,NSUBSET
  CALL SKIPCOM(1,'*')
  READ(1,*,IOSTAT=ISO) IS,IJHFRE(IS),HFREDAYBG(IS),HFREDUR(IS),HFREMIN(IS),NPNT(IS)
  IF(ISO>0) STOP 'SUBSET.INP: READING ERROR!'
  HFREDAY(IS) = HFREDAYBG(IS)
  HFREDAYEN(IS) = HFREDAYBG(IS) + HFREDUR(IS)/24
  ALLOCATE (HFREGRP(IS)%ICEL(NPNT(IS)),HFREGRP(IS)%JCEL(NPNT(IS)))
  ALLOCATE (HFREGRP(IS)%XCEL(NPNT(IS)),HFREGRP(IS)%YCEL(NPNT(IS)))
  DO NP=1,NPNT(IS)
    CALL SKIPCOM(1,'*')
    IF (IJHFRE(IS)==1) THEN
      READ(1,*,IOSTAT=ISO) HFREGRP(IS)%ICEL(NP),HFREGRP(IS)%JCEL(NP)
    ELSE
      READ(1,*,IOSTAT=ISO) HFREGRP(IS)%XCEL(NP),HFREGRP(IS)%YCEL(NP)
    ENDIF   
    IF(ISO>0) STOP 'SUBSET.INP: READING ERROR!'
  ENDDO
  IF (IJHFRE(IS)==0) CALL XY2IJ(HFREGRP(IS))
ENDDO
CLOSE(1)

CALL GETHFRE_HYD 
IF( ANY(ISTRAN(1:7)>0) ) CALL HFRE_WC     
IF(ISTRAN(8) > 0) CALL HFRE_WQ     

DEALLOCATE(HFREGRP)
DEALLOCATE(IJHFRE,HFREDAYBG,HFREDAYEN)
DEALLOCATE(HFREDUR,HFREDAY,HFREMIN,NPNT)

CALL FREEMEM

END SUBROUTINE
 
SUBROUTINE GETHFRE_HYD 
INTEGER(4)::NS,NCAL,ENDR,PMAX
INTEGER(4)::L,LN,K,NP,N,VER,HSIZE,KC1,ICEL,JCEL
REAL(4)   ::UTMPS,VTMPS,HPTMP(LCM)
REAL(8)   ::TIMEDAY,XCEL,YCEL
CHARACTER(200)::INPFILE,NSTR*3,NSTR1*7
CHARACTER(200),ALLOCATABLE::OUTFILE(:)

PMAX = MAXVAL(NPNT)
ALLOCATE(OUTFILE(PMAX))

WRITE(NSTR,'(I3)') 3*KC+3
SFMT = '('//NSTR//'F14.5)'
DO NS=1,NSUBSET
  IF (NGROUP>0 .AND. NS /= NGROUP) CYCLE
  WRITE(NSTR,'(I3.3)') NS
  INPFILE  = trim(OUTFOLDER)//'HFRE_HYD_'//TRIM(NSTR)//'.OUT'
  OPEN(10,FILE=INPFILE,ACTION='READ',STATUS='OLD',FORM='BINARY')
  DO NP=1,NPNT(NS)
    IF (NPOINT>0.AND.NP/=NPOINT) CYCLE
    WRITE(NSTR1,'(I3.3,A1,I3.3)') NS,'_',NP   
    OUTFILE(NP)  = trim(OUTFOLDER)//'HFREDAT\HFRE_HYD_'//TRIM(NSTR1)//'.DAT'   
    OPEN(11,FILE=OUTFILE(NP),ACTION='WRITE')
    WRITE(11,'(A)') 'TIMEDAY,BELV(L),HP(L),(U(L,K),V(L,K),W(L,K),K=1,KC)'
    CLOSE(11)
  ENDDO
  
  READ (10) VER,HSIZE
  READ (10) KC1
  READ (10) NPNT(NS)
  DO NP=1,NPNT(NS) 
    READ (10) ICEL,JCEL,XCEL,YCEL
  ENDDO
  ! ** end of header **
  
  DO WHILE(1)
    READ (10,END=100) TIMEDAY 
    DO NP=1,NPNT(NS)
      L = LIJ(HFREGRP(NS)%ICEL(NP),HFREGRP(NS)%JCEL(NP))
      READ(10) BELV(L),HPTMP(L),(U(L,K),V(L,K),W(L,K),K=1,KC)
      IF (NPOINT>0.AND.NP/=NPOINT) CYCLE
      OPEN(11,FILE=OUTFILE(NP),ACTION='WRITE',ACCESS='APPEND')
      WRITE(11,SFMT) TIMEDAY,BELV(L),HPTMP(L),(U(L,K),V(L,K),W(L,K),K=1,KC)
      CLOSE(11)
    ENDDO
  ENDDO
  100 CLOSE(10)
ENDDO
END SUBROUTINE

SUBROUTINE FREE_WC
  DEALLOCATE(SAL)
  DEALLOCATE(TEM)  
  DEALLOCATE(DYE)  
  DEALLOCATE(SFL)  
  DEALLOCATE(TOX)  
  DEALLOCATE(SED)  
  DEALLOCATE(SND)  
  DEALLOCATE(TEMB)
  DEALLOCATE(QQWV1)  
  DEALLOCATE(SEDDIA)  
  DEALLOCATE(KBT)  
  DEALLOCATE(TAUBSED)  
  DEALLOCATE(TAUBSND)  
  DEALLOCATE(TAUB)  
  DEALLOCATE(WVWHA)  
  DEALLOCATE(WVFRQL)  
  DEALLOCATE(WACCWE)  
  DEALLOCATE(WVDISP)  
  DEALLOCATE(WVHUU)  
  DEALLOCATE(WVHVV)  
  DEALLOCATE(WVHUV)  
  DEALLOCATE(TOXB)
  DEALLOCATE(HBED)  
  DEALLOCATE(BDENBED)  
  DEALLOCATE(PORBED)  
  DEALLOCATE(SEDB)  
  DEALLOCATE(SNDB)
  DEALLOCATE(CQBEDLOADX)  
  DEALLOCATE(CQBEDLOADY)  
  DEALLOCATE(VFRBED)  
  DEALLOCATE(SALA)
  DEALLOCATE(TEMA)  
  DEALLOCATE(DYEA)  
  DEALLOCATE(SFLA)  
  DEALLOCATE(TOXA)  
  DEALLOCATE(SEDA)  
  DEALLOCATE(SNDA)  
END SUBROUTINE

SUBROUTINE HFRE_WC 
  INTEGER(4)::NCAL,NSS
  INTEGER*4 NP,VER,HSIZE,KC,ICEL,JCEL
  INTEGER*4 IWQ(40), NACTIVE, NWQVAR
  INTEGER*4 NS,NW,MW,I,ALLOVAR
  INTEGER*4 L,K,ISYS,NT,NX,N1,NSXD
  REAL(4)::WQ
  REAL(8)::EETIME,XCEL,YCEL
  CHARACTER(200)::OUTFILE,NSTR*3,NSTR1*7
  
  ALLOVAR=0
  DO NSS=1,NSUBSET
    IF (NGROUP>0 .AND. NSS /= NGROUP) CYCLE
    WRITE(NSTR,'(I3.3)') NSS   
    WCFILEI  = trim(OUTFOLDER)//'HFRE_WC_'//TRIM(NSTR)//'.OUT'
    
    DO NP=1,NPNT(NSS)
      IF (NPOINT>0.AND.NP/=NPOINT) CYCLE
      WRITE(NSTR1,'(I3.3,A1,I3.3)') NSS,'_',NP
      IF(ISTRAN(1)==1) THEN
        SALTSF   = trim(OUTFOLDER)//'HFREDAT\SAL_TS_CELLS_'//TRIM(NSTR1)//'.DAT'
        OPEN(UOUTI(11),FILE=SALTSF,ACTION='WRITE')   !TSER
        WRITE(UOUTI(11),'(A)') '** EETIME,SAL(L,K) [PPT], GRP_CELL: '//TRIM(NSTR1)
        CLOSE(UOUTI(11))
      ENDIF
      IF(ISTRAN(2)==1) THEN
        TEMTSF   = trim(OUTFOLDER)//'HFREDAT\TEM_TS_CELLS_'//TRIM(NSTR1)//'.DAT'
        OPEN(UOUTI(12),FILE=TEMTSF,ACTION='WRITE')                     !TSER
        WRITE(UOUTI(12),'(A)') '** EETIME,TEM(L,K) [C], GRP_CELL: '//TRIM(NSTR1)  
        CLOSE(UOUTI(12))
      ENDIF
      IF(ISTRAN(3)==1) THEN
        DYETSF   = trim(OUTFOLDER)//'HFREDAT\DYE_TS_CELLS_'//TRIM(NSTR1)//'.DAT'
        OPEN(UOUTI(13),FILE=DYETSF,ACTION='WRITE')
        WRITE(UOUTI(13),'(A)') '** EETIME,DYE(L,K) [MG/L], GRP_CELL: '//TRIM(NSTR1)
        CLOSE(UOUTI(13))
      ENDIF
      IF(ISTRAN(4)==1) THEN
        SFLTSF   = trim(OUTFOLDER)//'HFREDAT\SFL_TS_CELLS_'//TRIM(NSTR1)//'.DAT'
        OPEN(UOUTI(14),FILE=SFLTSF,ACTION='WRITE')
        WRITE(UOUTI(14),'(A)') '** EETIME,SFL(L,K), GRP_CELL: '//TRIM(NSTR1)
        CLOSE(UOUTI(14))
      ENDIF
      IF(ISTRAN(5)==1) THEN
        TOXTSF  = trim(OUTFOLDER)//'HFREDAT\TOX_TS_CELLS_'//TRIM(NSTR1)//'.DAT'
        OPEN(UOUTI(15),FILE=TOXTSF,ACTION='WRITE')
        WRITE(UOUTI(15),'(A)') '** EETIME,TOX(L,K,NTOX) [MG/L], GRP_CELL: '//TRIM(NSTR1)
        CLOSE(UOUTI(15))
      ENDIF
      IF(ISTRAN(6)==1) THEN
        SEDTSF  = trim(OUTFOLDER)//'HFREDAT\SED_TS_CELLS_'//TRIM(NSTR1)//'.DAT'
        OPEN(UOUTI(16),FILE=SEDTSF,ACTION='WRITE')
        WRITE(UOUTI(16),'(A)') '** EETIME,SED(L,K,NSED) [MG/L], GRP_CELL: '//TRIM(NSTR1)
        CLOSE(UOUTI(16))
      ENDIF
      IF(ISTRAN(7)==1) THEN
        SNDTSF  = trim(OUTFOLDER)//'HFREDAT\SND_TS_CELLS_'//TRIM(NSTR1)//'.DAT'
        OPEN(UOUTI(17),FILE=SNDTSF,ACTION='WRITE')
        WRITE(UOUTI(17),'(A)') '** EETIME,(SND(L,K,NSND) [MG/L], GRP_CELL: '//TRIM(NSTR1)
        CLOSE(UOUTI(17))
      ENDIF
    ENDDO
    
    ! *** WATER COLUMN AND TOP LAYER OF SEDIMENT
    OPEN(95,FILE=WCFILEI,STATUS='UNKNOWN',ACCESS='SEQUENTIAL',FORM='BINARY')
    READ(95) VER,HSIZE             ! File Format Version and Header Size
    READ(95) (ISTRAN(I),I=1,7)
    READ(95) KC,NSED,NSND,NTOX
    READ(95) NPNT(NSS)             ! Number of stations
    DO NP=1,NPNT(NSS) 
      READ(95) ICEL,JCEL,XCEL,YCEL
    ENDDO
        
    NSXD=NSED+NSND
    
    IF (ALLOVAR==0) THEN  
      ALLOCATE(SAL(LA,KC))
      ALLOCATE(TEM(LA,KC))  
      ALLOCATE(DYE(LA,KC))  
      ALLOCATE(SFL(LA,KC))  
      ALLOCATE(TOX(LCM,KCM,NTXM))  
      ALLOCATE(SED(LCM,KCM,NSCM))  
      ALLOCATE(SND(LCM,KCM,NSNM))  
      ALLOCATE(TEMB(LA))
      ALLOCATE(QQWV1(LA))  
      ALLOCATE(SEDDIA(NSXD))  
      ALLOCATE(KBT(LA))  
      ALLOCATE(TAUBSED(LA))  
      ALLOCATE(TAUBSND(LA))  
      ALLOCATE(TAUB(LA))  
      ALLOCATE(WVWHA(LA))  
      ALLOCATE(WVFRQL(LA))  
      ALLOCATE(WACCWE(LA))  
      ALLOCATE(WVDISP(LA,KC))  
      ALLOCATE(WVHUU(LA,KC))  
      ALLOCATE(WVHVV(LA,KC))  
      ALLOCATE(WVHUV(LA,KC))  
      ALLOCATE(TOXB(LA,KBM,NTOX))
      ALLOCATE(HBED(LA,KBM))  
      ALLOCATE(BDENBED(LA,KBM))  
      ALLOCATE(PORBED(LA,KBM))  
      ALLOCATE(SEDB(LA,KBM,NSED))  
      ALLOCATE(SNDB(LA,KBM,NSND))
      ALLOCATE(CQBEDLOADX(LA,NSND))  
      ALLOCATE(CQBEDLOADY(LA,NSND))  
      ALLOCATE(VFRBED(LA,KBM,NSTM))  
      ALLOCATE(SALA(LA))
      ALLOCATE(TEMA(LA))  
      ALLOCATE(DYEA(LA))  
      ALLOCATE(SFLA(LA))  
      ALLOCATE(TOXA(LCM,NTXM))  
      ALLOCATE(SEDA(LCM,NSCM))  
      ALLOCATE(SNDA(LCM,NSNM))  
      ALLOVAR=1
    ENDIF
        
    DO WHILE(1)
      ! *** WATER COLUMN AND TOP LAYER OF SEDIMENT
      READ(95,END=100) EETIME,NACTIVE
      IF(ISTRAN(6) == 1 .OR. ISTRAN(7) >= 1)THEN
        DO NP=1,NPNT(NSS) 
          L = LIJ(HFREGRP(NSS)%ICEL(NP),HFREGRP(NSS)%JCEL(NP))
          READ(95)KBT(L)
        ENDDO
      ENDIF
      
      ! *** WRITE THE WATER COLUMN AND TOP LAYER OF SEDIMENT DATA, IF NEEDED
      DO NP=1,NPNT(NSS)       
        L = LIJ(HFREGRP(NSS)%ICEL(NP),HFREGRP(NSS)%JCEL(NP))
        IF(ISTRAN(1) == 1) THEN
          READ(95)(SAL(L,K),K=1,KC)
          IF (NPOINT==0.OR.(NP==NPOINT)) THEN         
            N1=KBT(L) 
            WRITE(NSTR1,'(I3.3,A1,I3.3)') NSS,'_',NP
            SALTSF   = trim(OUTFOLDER)//'HFREDAT\SAL_TS_CELLS_'//TRIM(NSTR1)//'.DAT'
            OPEN(UOUTI(11),FILE=SALTSF,ACTION='WRITE',ACCESS='APPEND')
            WRITE(UOUTI(11),'(101F14.5)') REAL(EETIME),(SAL(L,K),K=1,KC)
            CLOSE(UOUTI(11))
          ENDIF
        ENDIF
        
        IF(ISTRAN(2) == 1)THEN
          READ(95)(TEM(L,K),K=1,KC)       
          IF (NPOINT==0.OR.(NP==NPOINT)) THEN         
            WRITE(NSTR1,'(I3.3,A1,I3.3)') NSS,'_',NP
            TEMTSF   = trim(OUTFOLDER)//'HFREDAT\TEM_TS_CELLS_'//TRIM(NSTR1)//'.DAT'
            OPEN(UOUTI(12),FILE=TEMTSF,ACTION='WRITE',ACCESS='APPEND')
            WRITE(UOUTI(12),'(101F14.5)') REAL(EETIME),(TEM(L,K),K=1,KC)
            CLOSE(UOUTI(12)) 
          ENDIF        
        ENDIF
        
        IF(ISTRAN(3) == 1) THEN
          READ(95,ERR=999,IOSTAT=ISYS)(DYE(L,K),K=1,KC)         
          IF (NPOINT==0.OR.(NP==NPOINT)) THEN         
            WRITE(NSTR1,'(I3.3,A1,I3.3)') NSS,'_',NP
            DYETSF   = trim(OUTFOLDER)//'HFREDAT\DYE_TS_CELLS_'//TRIM(NSTR1)//'.DAT'
            OPEN(UOUTI(13),FILE=DYETSF,ACTION='WRITE',ACCESS='APPEND')
            WRITE(UOUTI(13),'(101F14.5)') REAL(EETIME),(DYE(L,K),K=1,KC)
            CLOSE(UOUTI(13))
          ENDIF
        ENDIF
        
        IF(ISTRAN(4) == 1) THEN
          READ(95)(SFL(L,K),K=1,KC)
          IF (NPOINT==0.OR.(NP==NPOINT)) THEN      
            WRITE(NSTR1,'(I3.3,A1,I3.3)') NSS,'_',NP
            SFLTSF   = trim(OUTFOLDER)//'HFREDAT\SFL_TS_CELLS_'//TRIM(NSTR1)//'.DAT'
            OPEN(UOUTI(14),FILE=SFLTSF,ACTION='WRITE',ACCESS='APPEND')
            WRITE(UOUTI(14),'(101F14.5)') REAL(EETIME),(SFL(L,K),K=1,KC)
            CLOSE(UOUTI(14))
          ENDIF
        ENDIF
        
        IF(ISTRAN(5) == 1)THEN
          READ(95)((TOX(L,K,NT),K=1,KC),NT=1,NTOX)
          IF (NPOINT==0.OR.(NP==NPOINT)) THEN
            WRITE(NSTR1,'(I3.3,A1,I3.3)') NSS,'_',NP
            TOXTSF  = trim(OUTFOLDER)//'HFREDAT\TOX_TS_CELLS_'//TRIM(NSTR1)//'.DAT'
            OPEN(UOUTI(15),FILE=TOXTSF,ACTION='WRITE',ACCESS='APPEND')
            WRITE(UOUTI(15),'(101F14.5)') REAL(EETIME),((TOX(L,K,NT),K=1,KC),NT=1,NTOX)
            CLOSE(UOUTI(15))
          ENDIF
        ENDIF
        
        IF(ISTRAN(6) == 1)THEN
          READ(95)((SED(L,K,NS),K=1,KC),NS=1,NSED)
          IF (NPOINT==0.OR.(NP==NPOINT)) THEN
            WRITE(NSTR1,'(I3.3,A1,I3.3)') NSS,'_',NP
            SEDTSF  = trim(OUTFOLDER)//'HFREDAT\SED_TS_CELLS_'//TRIM(NSTR1)//'.DAT'
            OPEN(UOUTI(16),FILE=SEDTSF,ACTION='WRITE',ACCESS='APPEND')
            WRITE(UOUTI(16),'(101F14.5)') REAL(EETIME),((SED(L,K,NS),K=1,KC),NS=1,NSED)
            CLOSE(UOUTI(16))
          ENDIF
        ENDIF
        
        IF(ISTRAN(7) == 1)THEN
          READ(95)((SND(L,K,NX),K=1,KC),NX=1,NSND)
          IF (NPOINT==0.OR.(NP==NPOINT)) THEN
            WRITE(NSTR1,'(I3.3,A1,I3.3)') NSS,'_',NP
            SNDTSF  = trim(OUTFOLDER)//'HFREDAT\SND_TS_CELLS_'//TRIM(NSTR1)//'.DAT'
            OPEN(UOUTI(17),FILE=SNDTSF,ACTION='WRITE',ACCESS='APPEND')
            WRITE(UOUTI(17),'(101F14.5)') REAL(EETIME),((SND(L,K,NX),K=1,KC),NX=1,NSND)
            CLOSE(UOUTI(17))
          ENDIF
        ENDIF    
      ENDDO
    ENDDO
    100 CLOSE(95)  
  ENDDO
  CALL FREE_WC
  RETURN
  999 PRINT*,TRIM(WCFILEI)//': READING ERROR'
  STOP
END SUBROUTINE

SUBROUTINE HFRE_WQ
  IMPLICIT NONE
  INTEGER(4)::NCAL,NSS
  INTEGER*4 NP,N
  INTEGER*4 IWQ(40), NACTIVE, NWQVAR
  INTEGER*4 NS,NW,MW
  INTEGER*4 L,K,KC,ICEL,JCEL
  INTEGER*4 VER,HSIZE
  REAL(8):: EETIME,XCEL,YCEL
  REAL(4),ALLOCATABLE::WQ(:,:)
  CHARACTER(50)::NSTR*3,NSTR1*7,TSFILE*200

    CHCTSF = 'CHC_TS_CELLS.DAT'
    CHDTSF = 'CHD_TS_CELLS.DAT'
    CHGTSF = 'CHG_TS_CELLS.DAT'
    ROCTSF = 'ROC_TS_CELLS.DAT'
    LOCTSF = 'LOC_TS_CELLS.DAT'
    DOCTSF = 'DOC_TS_CELLS.DAT'
    ROPTSF = 'ROP_TS_CELLS.DAT'
    LOPTSF = 'LOP_TS_CELLS.DAT'
    DOPTSF = 'DOP_TS_CELLS.DAT'
    P4DTSF = 'P4D_TS_CELLS.DAT'
    RONTSF = 'RON_TS_CELLS.DAT'
    LONTSF = 'LON_TS_CELLS.DAT'
    DONTSF = 'DON_TS_CELLS.DAT'
    NHXTSF = 'NHX_TS_CELLS.DAT'
    NOXTSF = 'NOX_TS_CELLS.DAT'
    SUUTSF = 'SUU_TS_CELLS.DAT'
    SAATSF = 'SAA_TS_CELLS.DAT'
    CODTSF = 'COD_TS_CELLS.DAT'
    DOXTSF = 'DOX_TS_CELLS.DAT'
    TAMTSF = 'TAM_TS_CELLS.DAT'
    FCBTSF = 'FCB_TS_CELLS.DAT'
    CO2TSF = 'CO2_TS_CELLS.DAT'
    MACTSF = 'MAC_TS_CELLS.DAT'
    
    TSWQF(1:23) = (/CHCTSF,CHDTSF,CHGTSF,ROCTSF,LOCTSF,DOCTSF,ROPTSF,LOPTSF,&
                  DOPTSF,P4DTSF,RONTSF,LONTSF,DONTSF,NHXTSF,NOXTSF,SUUTSF,SAATSF,CODTSF,&
                  DOXTSF,TAMTSF,FCBTSF,CO2TSF,MACTSF /)
                  
  DO NSS=1,NSUBSET
    IF (NGROUP>0 .AND. NSS /= NGROUP) CYCLE
    WRITE(NSTR,'(I3.3)') NSS
    WQFILEI  = trim(OUTFOLDER)//'HFRE_WQ_'//TRIM(NSTR)//'.OUT'
    
    ! *** WATER QUALITY MODEL (HEM3D) RESULTS
    OPEN(95,FILE=WQFILEI,STATUS='UNKNOWN',ACCESS='SEQUENTIAL',FORM='BINARY')   
    READ(95) VER,HSIZE  
    READ(95) KC,NWQVAR   
    ALLOCATE(WQ(KC,NWQVAR))  
    READ(95) NPNT(NSS)
    DO NP=1,NPNT(NSS) 
      READ(95) ICEL,JCEL,XCEL,YCEL
    ENDDO   
    READ(95)(IWQ(NW),NW=1,NWQVAR) 
    ! ** END HEADER
    
    DO NP=1,NPNT(NSS)    
      IF (NPOINT>0.AND.NP/=NPOINT) CYCLE
      DO N=1,NWQVAR
        IF (IWQ(N)>=1) THEN        
          WRITE(NSTR1,'(I3.3,A1,I3.3)') NSS,'_',NP
          TSFILE = trim(OUTFOLDER)//'HFREDAT\'//TRIM(TSWQF(N))//'_'//TRIM(NSTR1)//'.DAT'
          OPEN(UOUTI(N),FILE=TSFILE,ACTION='WRITE')
          WRITE(UOUTI(N),'(A)') 'JULTIME,('//TSWQF(N)(1:3)//'(K),K=1,KC),GRP_CELL: '//TRIM(NSTR1)
          CLOSE(UOUTI(N))
        ENDIF
      ENDDO
    ENDDO
    
    WQ = -999
    DO WHILE(1)
      READ(95,END=100)EETIME
      DO NP=1,NPNT(NSS)
      DO K=1,KC
        DO NW=1,NWQVAR
          IF(IWQ(NW) > 0)THEN
            READ(95)WQ(K,NW)
          ENDIF
        ENDDO
      ENDDO
      ENDDO
      
      DO NP=1,NPNT(NSS) 
        IF (NPOINT>0.AND.NP/=NPOINT) CYCLE
        DO NW=1,NWQVAR
          IF(IWQ(NW) > 0) THEN
            WRITE(NSTR1,'(I3.3,A1,I3.3)') NSS,'_',NP
            TSFILE = trim(OUTFOLDER)//'HFREDAT\'//TRIM(TSWQF(NW))//'_'//TRIM(NSTR1)//'.DAT'
            OPEN(UOUTI(NW),FILE=TSFILE,ACTION='WRITE',ACCESS='APPEND')
            WRITE(UOUTI(NW),'(101F14.5)') REAL(EETIME),(WQ(K,NW),K=1,KC)
            CLOSE(UOUTI(NW))
          ENDIF
        ENDDO
      ENDDO
    ENDDO
    100 CLOSE(95)
    DEALLOCATE(WQ)
  ENDDO
  RETURN
  999 PRINT*,TRIM(WQFILEI)//': READING ERROR'
  STOP
  
END SUBROUTINE

END MODULE
