MODULE GLOBALVARS
 
 INTEGER(4),PARAMETER:: RK=8,RKD=8,IK4=4
 REAL(RK),  PARAMETER:: PI=3.14159265358979_RK
 REAL(4),   PARAMETER:: BLK =-999
 INTEGER(4),PARAMETER:: NTSWQVM=23  !VB NTSWQVM CHANGED FROM 22 TO 23 TO ACCOMODATE CO2 & MAC

 INTEGER(4),PARAMETER::UETA = 1
 INTEGER(4),PARAMETER::UOUT = 2
 INTEGER(4),PARAMETER::UERR = 3
 INTEGER(4),PARAMETER::UTEC = 4       
 INTEGER(4),PARAMETER::UMAT = 5       
 INTEGER(4),PARAMETER::UFRM = 6       
 INTEGER(4),PARAMETER::UTBL = 7       
 INTEGER(4),PARAMETER::ULOC = 8       
 INTEGER(4),PARAMETER::UHSI = 9       
 INTEGER(4),PARAMETER::UPDI = 10      
 INTEGER(4),PARAMETER::URTP = 11      
 INTEGER(4),PARAMETER::UWET = 12      
 INTEGER(4),PARAMETER::USWN = 13      
 INTEGER(4),PARAMETER::USXX = 14
 INTEGER(4),PARAMETER::USXY = 15
 INTEGER(4),PARAMETER::USYY = 16
 INTEGER(4),PARAMETER::UDIS = 17
 INTEGER(4),PARAMETER::UBOT = 18
 INTEGER(4),PARAMETER::ULIJ = 19
 INTEGER(4),PARAMETER::UGRD = 20
 INTEGER(4),PARAMETER::UDXY = 21
 INTEGER(4),PARAMETER::UINP = 22
 INTEGER(4),PARAMETER::UCGRD = 23
 INTEGER(4),PARAMETER::UCLIS = 24
 INTEGER(4),PARAMETER::UHEI  = 25
 INTEGER(4),PARAMETER::UPER  = 26
 INTEGER(4),PARAMETER::WVBL  = 27
 INTEGER(4),PARAMETER::WVEI  = 28
 INTEGER(4),PARAMETER::UWSI  = 29
 INTEGER(4),PARAMETER::UVEI  = 30
 INTEGER(4),PARAMETER::UWSE  = 31
 INTEGER(4),PARAMETER::UVEL  = 32  
 INTEGER(4),PARAMETER::UCOR  = 33
 INTEGER(4),PARAMETER::UWCI  = 34
 INTEGER(4),PARAMETER::UWQI  = 35
 INTEGER(4),PARAMETER::UWQO  = 36
 INTEGER(4),PARAMETER::UWSO  = 37
 INTEGER(4),PARAMETER::UVEO  = 38
 INTEGER(4),PARAMETER::UWCO  = 39
 INTEGER(4),PARAMETER::UNNC  = 40
 INTEGER(4),PARAMETER::UNAS  = 41
 INTEGER(4),PARAMETER::UTEC1 = 42
 INTEGER(4),PARAMETER::UTEC2 = 43
 INTEGER(4),PARAMETER::UTEC3 = 44
 INTEGER(4),PARAMETER::UTEC4 = 45
 INTEGER(4),PARAMETER::UPROF = 46
 INTEGER(4),PARAMETER::UDAT1 = 47
 INTEGER(4),PARAMETER::UDAT2 = 48
 INTEGER(4),PARAMETER::ULGR  = 49
 INTEGER(4),PARAMETER::WSLIS = 50
 INTEGER(4),PARAMETER::VELIS = 51
 INTEGER(4),PARAMETER::UTEC5 = 52
 INTEGER(4),PARAMETER::UICE  = 53
 INTEGER(4),PARAMETER::UTMP  = 100
 
 CHARACTER(200)::SWNFILE
 CHARACTER(200)::FRMFILE
 CHARACTER(200)::TBLFILE
 CHARACTER(200)::LOCFILE
 CHARACTER(200)::MATFILE
 CHARACTER(200)::TECFILE
 CHARACTER(200)::EFDCFILE
 CHARACTER(200)::HSIFILE
 CHARACTER(200)::PDIFILE
 CHARACTER(200)::RTPFILE
 CHARACTER(200)::WETFILE
 CHARACTER(200)::SXXFILE
 CHARACTER(200)::SXYFILE
 CHARACTER(200)::SYYFILE
 CHARACTER(200)::DISFILE
 CHARACTER(200)::SWNINPF
 CHARACTER(200)::SWNOUTF
 CHARACTER(200)::GRDFILE
 CHARACTER(200)::LXLYFILE
 CHARACTER(200)::BOTFILE
 CHARACTER(200)::DXDYFILE
 CHARACTER(200)::INPFILE
 CHARACTER(200)::OUTFILE
 CHARACTER(200)::WSFILE
 CHARACTER(200)::WSFILE2
 CHARACTER(200)::CELLGRDF
 CHARACTER(200)::CELISTF
 CHARACTER(200)::WHEIFILE
 CHARACTER(200)::WPERFILE
 CHARACTER(200)::LIJXYFILE
 CHARACTER(200)::TWFILE
 CHARACTER(200)::VELFILE
 CHARACTER(200)::WBLFILE
 CHARACTER(200)::LCELL
 CHARACTER(200)::ROOTFILE
 CHARACTER(200)::DATFILE
 CHARACTER(200)::P2DFILE
 CHARACTER(200)::SGZFILE
 CHARACTER(200)::BEFILEI

 INTEGER(4)    ::MATCHK
 INTEGER(4)    ::TECCHK
 INTEGER(4)    ::GRPCHK
 INTEGER(4)    ::LOCCHK
 INTEGER(4)    ::HFRMN
 INTEGER(4)    ::DFRMN
 INTEGER(4)    ::HTBLN
 INTEGER(4)    ::DTBLN 
 INTEGER(4)    ::RFRMN 
 INTEGER(4)    ::RTBLN 
 INTEGER(4)    ::WLFRMN 
 INTEGER(4)    ::WLTBLN 
 INTEGER(4)    ::HPTBLN
 INTEGER(4)    ::DITBLN
 INTEGER(4)    ::I1
 INTEGER(4)    ::J1
 INTEGER(4)    ::JN
 INTEGER(4)    ::IPMAX     !FROM TECPLOT OUTPUT
 INTEGER(4)    ::JPMAX     !FROM TECPLOT OUTPUT
 INTEGER(4)    ::LCELMAX
 INTEGER(4)    ::SNAPSHOT
 INTEGER(4)    ::KTI
 INTEGER(4)    ::NGWSER
 INTEGER(4)    ::ISGWIT
 INTEGER(4)    ::WSVER  !101: EFDC 6.0-7.0/ 102: EFDC 7.1/7201: EFDC 7.2/7300: EFDC 7.3-8.2/10000: EFDCPP
 
 REAL(RK)       ::DX
 REAL(RK)       ::DY
 REAL(RK)       ::X0
 REAL(RK)       ::Y0
 REAL(RK)       ::LATI
 REAL(RK)       ::SA
 REAL(RK)       ::TE
 REAL(RK)       ::TIME

 INTEGER(4),ALLOCATABLE::LAP(:)
 INTEGER(4),ALLOCATABLE::IJ(:)

 REAL(RK),  ALLOCATABLE::WDX(:)
 REAL(RK),  ALLOCATABLE::WDY(:)
 REAL(RK),  ALLOCATABLE::XBOT(:,:)
 REAL(RK),  ALLOCATABLE::YBOT(:,:)

 !************************************************************************
 REAL(RK),  ALLOCATABLE::UDEP(:,:)
 REAL(RK),  ALLOCATABLE::VDEP(:,:)
 REAL(RK)  ::ACTIVE
 REAL(RK)  ::ROTA					            !ROTATION (DEG)
 REAL(RK)  ::MEANSEA		        	    !MEAN SEA LEVEL [M]
 REAL(RK)  ::ZBMAX					          !MAXIMUM BATHYMETRY
 INTEGER(4)::MAX2					            !NUMBER OF ACTIVE POINTS IN 2D
 INTEGER(4)::NBC					            !NUMBER OF BOUNDARY POINTS
 INTEGER(4)::ZONE				              !CENTRAL MERIDIAN

!**************************************************************************
 REAL(RK)     ::RHO
 REAL(RK)     ::RHOS
 REAL(RK)     ::RHOS1
 REAL(RK)     ::KS        !NIKURADSE: KS=2.5D50
 REAL(RK)     ::KA
 REAL(RK)     ::D50
 REAL(RK)     ::BW
 REAL(RK)     ::WT
 REAL(RK)     ::WHMIN
 REAL(RK)     ::WHMAX
 REAL(RK)     ::DWH
 REAL(RK)     ::HLAND          !IN METRE
 REAL(RK)     ::FACTOR
 REAL(RK)     ::OME
 REAL(RK)     ::DEP
 
 INTEGER(4)   ::DISPLAY_ON
 INTEGER(4)   ::NREAD_SW
 INTEGER(4)   ::NREAD_REC
 INTEGER(4)   ::NREAD_CUR
 INTEGER(4)   ::NREAD_GWS

 CHARACTER(200)::DEPFILE
 CHARACTER(200)::ERROMES
 
 LOGICAL(4)    ::READY_BS
 LOGICAL(4)    ::READY_SW
 LOGICAL(4)    ::READY_REC
 LOGICAL(4)    ::READY_CUR
 LOGICAL(4)    ::READY_GWS
 LOGICAL(1)    ::TMES
 LOGICAL(4)    ::RECCHK
 LOGICAL(4)    ::CURCHK
 LOGICAL(4)    ::ZOBCHK
 LOGICAL(4)    ::VPROFCHK
 LOGICAL(4)    ::TECCHKL
 LOGICAL(4)    ::READY_TSW
 LOGICAL(4)    ::READY_GTW
 LOGICAL(4)    ::READY_TCR
 LOGICAL(4)    ::READY_EES
 LOGICAL(4)    ::READY_SWN

 ! *** EESWAN ***

  INTEGER(4)  ::IC
  INTEGER(4)  ::JC
  INTEGER(4)  ::KC
  INTEGER(4)  ::LC
  INTEGER(4)  ::ICM
  INTEGER(4)  ::JCM
  INTEGER(4)  ::KCM
  INTEGER(4)  ::LCM
  INTEGER(4)  ::LVC
  INTEGER(4)  ::ISCLO
  INTEGER(4)  ::NDM
  INTEGER(4)  ::LDM
  INTEGER(4)  ::ISMASK
  INTEGER(4)  ::ISCONNECT
  INTEGER(4)  ::KSM
  INTEGER(4)  ::LA
  INTEGER(4)  ::NP
  INTEGER(4)  ::SWANGRP
  INTEGER(4)  ::RLS_OP
  INTEGER(4)  ::NTM              !Number of Snapshot
  INTEGER(4)  ::NPNSBP
  INTEGER(4)  ::NPEWBP
  INTEGER(4)  ::IGRIDV
  INTEGER(4)  ::ISPD
  INTEGER(4)  ::KMINV
 
  REAL(4)     ::JULTIME
  REAL(4)     ::BELADJ
  REAL(4)     ::BELCVRT
  REAL(4)     ::XMIN
  REAL(4)     ::YMIN
  REAL(4)     ::XMAX
  REAL(4)     ::YMAX
     
  INTEGER(4),ALLOCATABLE ::IJCT(:,:)
  INTEGER(4),ALLOCATABLE ::LIJ(:,:)
  INTEGER(4),ALLOCATABLE ::LCT(:)
  INTEGER(4),ALLOCATABLE ::IL(:)
  INTEGER(4),ALLOCATABLE ::JL(:)
  INTEGER(4),ALLOCATABLE ::KBT(:)
  INTEGER(4),ALLOCATABLE ::LNC(:)
  INTEGER(4),ALLOCATABLE ::LSC(:)
  INTEGER(4),ALLOCATABLE ::LEC(:)
  INTEGER(4),ALLOCATABLE ::LWC(:)
  INTEGER(4),ALLOCATABLE ::LNEC(:)
  INTEGER(4),ALLOCATABLE ::LNWC(:)
  INTEGER(4),ALLOCATABLE ::LSEC(:)
  INTEGER(4),ALLOCATABLE ::LSWC(:)
  
  INTEGER(4),ALLOCATABLE ::NSET(:)
  INTEGER(4),ALLOCATABLE ::KSZ(:)

  INTEGER(4),ALLOCATABLE ::ISPNS(:)  
  INTEGER(4),ALLOCATABLE ::JSPNS(:)  
  INTEGER(4),ALLOCATABLE ::INPNS(:)  
  INTEGER(4),ALLOCATABLE ::JNPNS(:)  
  INTEGER(4),ALLOCATABLE ::IWPEW(:)
  INTEGER(4),ALLOCATABLE ::JWPEW(:)
  INTEGER(4),ALLOCATABLE ::IEPEW(:)
  INTEGER(4),ALLOCATABLE ::JEPEW(:)
  
  REAL(4),   ALLOCATABLE ::CUE(:)
  REAL(4),   ALLOCATABLE ::CUN(:)
  REAL(4),   ALLOCATABLE ::CVE(:)
  REAL(4),   ALLOCATABLE ::CVN(:)
  REAL(4),   ALLOCATABLE ::RSSBCE(:)
  REAL(4),   ALLOCATABLE ::RSSBCN(:)
  REAL(4),   ALLOCATABLE ::RSSBCS(:)
  REAL(4),   ALLOCATABLE ::RSSBCW(:)

  REAL(4),   ALLOCATABLE ::BELV(:)  
  REAL(4),   ALLOCATABLE ::HPT(:,:)
  REAL(8),   ALLOCATABLE ::HP0(:)

  REAL(4),   ALLOCATABLE ::HSIG(:)
  REAL(4),   ALLOCATABLE ::DIR(:)
  REAL(4),   ALLOCATABLE ::RTP(:)
  REAL(4),   ALLOCATABLE ::RLS(:)
  REAL(4),   ALLOCATABLE ::EDIS(:)
  REAL(4),   ALLOCATABLE ::SXX(:)
  REAL(4),   ALLOCATABLE ::SXY(:)
  REAL(4),   ALLOCATABLE ::SYY(:)
  REAL(4),   ALLOCATABLE ::WVENE(:)
  
  REAL(4),   ALLOCATABLE ::HSP(:)
  REAL(4),   ALLOCATABLE ::DIRP(:)
  REAL(4),   ALLOCATABLE ::RTPP(:)
  REAL(4),   ALLOCATABLE ::RLSP(:)
  REAL(4),   ALLOCATABLE ::EDISP(:)
  REAL(4),   ALLOCATABLE ::SXXP(:)
  REAL(4),   ALLOCATABLE ::SXYP(:)
  REAL(4),   ALLOCATABLE ::SYYP(:)
  REAL(4),   ALLOCATABLE ::XP(:)
  REAL(4),   ALLOCATABLE ::YP(:)
  
  REAL(4),   ALLOCATABLE ::JTIME(:)
  REAL(4),   ALLOCATABLE ::WSE(:,:)
  REAL(4),   ALLOCATABLE ::VXA(:,:)
  REAL(4),   ALLOCATABLE ::VYA(:,:)

  REAL(4),   ALLOCATABLE ::U(:,:)
  REAL(4),   ALLOCATABLE ::V(:,:)
  REAL(4),   ALLOCATABLE ::W(:,:)
  REAL(4),   ALLOCATABLE ::UK(:,:)
  REAL(4),   ALLOCATABLE ::VK(:,:)

  REAL(4),   ALLOCATABLE ::XCC(:)
  REAL(4),   ALLOCATABLE ::YCC(:)
  REAL(4),   ALLOCATABLE ::ZINT(:)
  REAL(4),   ALLOCATABLE ::ZSIG(:)
  REAL(4),   ALLOCATABLE ::ARR(:)
    
  CHARACTER(200)::CELLFILE
  CHARACTER(200)::MAPNSFILE
  CHARACTER(200)::MAPEWFILE
  CHARACTER(200)::WSFILEI
  CHARACTER(200)::VEFILEI
  CHARACTER(200)::HYFILEI
  CHARACTER(200)::INPFOLDER
  CHARACTER(200)::WORKPATH 
  CHARACTER(200)::WSEFILE 
  CHARACTER(200)::WVEFILE
  CHARACTER(200)::WINPFILE
  CHARACTER(200)::SETSFILE
  CHARACTER(200)::LPTFILE
  CHARACTER(200)::BCFILEI
  
  ! *** GetEFDC ***
  LOGICAL(4) ::LSEDZLJ
  LOGICAL(4) ::ready_extr

  INTEGER(4)  ::ISTRAN(0:8)
  INTEGER(4)  ::ISSPH(8)
  INTEGER(4)  ::NPSPH(8)
  INTEGER(4)  ::UOUTI(100)  !31
  INTEGER(4)  ::NLOC
  INTEGER(4)  ::LAYK
  INTEGER(4)  ::ZOPT
  INTEGER(4)  ::ROT
  INTEGER(4)  ::LCMWQ
  INTEGER(4)  ::VPROFILE
  INTEGER(4)  ::UCVPRF(NTSWQVM)
  INTEGER(4)  ::ISTRWQ(NTSWQVM)

  INTEGER(4),ALLOCATABLE ::ICEL(:)
  INTEGER(4),ALLOCATABLE ::JCEL(:)

  REAL(8),   ALLOCATABLE ::XCEL(:)                 
  REAL(8),   ALLOCATABLE ::YCEL(:)                 
  REAL(8),   ALLOCATABLE ::XCOR(:,:)               
  REAL(8),   ALLOCATABLE ::YCOR(:,:)               
  REAL(8),   ALLOCATABLE ::AREA(:)

  CHARACTER(2 ) ::SSTR2,SSTR3
  CHARACTER(10) ::SSTR1
  CHARACTER(20) ::SFMT
  CHARACTER(20) ::SFMT1
  CHARACTER(20) ::SFMT2
  CHARACTER(20) ::SFMT3
  CHARACTER(20) ::SFMT4
  CHARACTER(20) ::SINDEX
  CHARACTER(100)::SIX
  CHARACTER(100)::SJY
  CHARACTER(100)::NDRIFTER

  CHARACTER(200)::IJFile
  CHARACTER(200)::CORNFILE
  CHARACTER(200)::ASERFILE
  CHARACTER(200)::WCFILEI
  CHARACTER(200)::WQFILEI
  CHARACTER(200)::WSFILEO
  CHARACTER(200)::VEFILEO
  CHARACTER(200)::WQFILEO
  CHARACTER(200)::SALLAYF 
  CHARACTER(200)::TEMLAYF
  CHARACTER(200)::DYELAYF
  CHARACTER(200)::SFLLAYF
  CHARACTER(200)::TOXLAYF
  CHARACTER(200)::TOXBLAYF
  CHARACTER(200)::SEDLAYF
  CHARACTER(200)::SEDBLAYF
  CHARACTER(200)::SNDLAYF
  CHARACTER(200)::SNDBLAYF
  CHARACTER(200)::TSWSF
  CHARACTER(200)::TSICF
  CHARACTER(200)::TSVEF
  CHARACTER(200)::SALTSF
  CHARACTER(200)::TEMTSF
  CHARACTER(200)::DYETSF
  CHARACTER(200)::SFLTSF
  CHARACTER(200)::TOXTSF
  CHARACTER(200)::TOXBTSF
  CHARACTER(200)::SEDTSF
  CHARACTER(200)::SEDBTSF
  CHARACTER(200)::SNDTSF
  CHARACTER(200)::SNDBTSF
  CHARACTER(200)::CHCTSF
  CHARACTER(200)::CHDTSF
  CHARACTER(200)::CHGTSF
  CHARACTER(200)::ROCTSF
  CHARACTER(200)::LOCTSF
  CHARACTER(200)::DOCTSF
  CHARACTER(200)::ROPTSF
  CHARACTER(200)::LOPTSF
  CHARACTER(200)::DOPTSF
  CHARACTER(200)::P4DTSF
  CHARACTER(200)::RONTSF
  CHARACTER(200)::LONTSF
  CHARACTER(200)::DONTSF
  CHARACTER(200)::NHXTSF
  CHARACTER(200)::NOXTSF
  CHARACTER(200)::SUUTSF
  CHARACTER(200)::SAATSF
  CHARACTER(200)::CODTSF
  CHARACTER(200)::DOXTSF
  CHARACTER(200)::TAMTSF
  CHARACTER(200)::FCBTSF
  CHARACTER(200)::CO2TSF
  CHARACTER(200)::MACTSF
  CHARACTER(200)::TSBCF
  CHARACTER(200)::TSWQF(NTSWQVM)
  
  CHARACTER(200)::VELPROFILE
  CHARACTER(200)::SALPROFILE
  CHARACTER(200)::TEMPROFILE
  CHARACTER(200)::DYEPROFILE
  CHARACTER(200)::TOXPROFILE
  CHARACTER(200)::SEDPROFILE
  CHARACTER(200)::SNDPROFILE
  CHARACTER(200)::CHCTSFPROF
  CHARACTER(200)::CHDTSFPROF
  CHARACTER(200)::CHGTSFPROF
  CHARACTER(200)::ROCTSFPROF
  CHARACTER(200)::LOCTSFPROF
  CHARACTER(200)::DOCTSFPROF
  CHARACTER(200)::ROPTSFPROF
  CHARACTER(200)::LOPTSFPROF
  CHARACTER(200)::DOPTSFPROF
  CHARACTER(200)::P4DTSFPROF
  CHARACTER(200)::RONTSFPROF
  CHARACTER(200)::LONTSFPROF
  CHARACTER(200)::DONTSFPROF
  CHARACTER(200)::NHXTSFPROF
  CHARACTER(200)::NOXTSFPROF
  CHARACTER(200)::SUUTSFPROF
  CHARACTER(200)::SAATSFPROF
  CHARACTER(200)::CODTSFPROF
  CHARACTER(200)::DOXTSFPROF
  CHARACTER(200)::TAMTSFPROF
  CHARACTER(200)::FCBTSFPROF
  CHARACTER(200)::OUTFOLDER
  CHARACTER(200)::DRIFILE
  CHARACTER(200)::TUFILEI
  
  INTEGER(4)  ::NSED
  INTEGER(4)  ::NSNM
  INTEGER(4)  ::NSND
  INTEGER(4)  ::KB
  INTEGER(4)  ::KBM
  INTEGER(4)  ::NDYE
  INTEGER(4)  ::NTOX
  INTEGER(4)  ::NTXM
  INTEGER(4)  ::NSTM
  INTEGER(4)  ::ITBM
  INTEGER(4)  ::NSICM
  INTEGER(4)  ::ISBEXP
  INTEGER(4)  ::NWQV
  INTEGER(4)  ::ISBEDSTR
  INTEGER(4)  ::ISBDLDBC
  INTEGER(4)  ::NSCM
  INTEGER(4)  ::ISINWV
  INTEGER(4)  ::NTSPTC
  INTEGER(4)  ::NTMWC            !Number of Snapshot FOR WC
  INTEGER(4)  ::NSEDFLUME
  INTEGER(4)  ::ISEDINT
  INTEGER(4)  ::ISEDBINT
  INTEGER(4)  ::ISEDWC
  INTEGER(4)  ::ISMUD
  INTEGER(4)  ::ISNDWC
  INTEGER(4)  ::ISEDVW
  INTEGER(4)  ::ISNDVW
  INTEGER(4)  ::ISDTXBUG
  INTEGER(4)  ::MTIDE
  INTEGER(4)  ::NWSER
  INTEGER(4)  ::NASER
  INTEGER(4)  ::ISCHAN
  INTEGER(4)  ::ISWAVE
  INTEGER(4)  ::RML
  INTEGER(4)  ::VER_WQ
  INTEGER(4)  ::nread_extr
  INTEGER(4)  ::ALLSNAP
  INTEGER(4)  ::NSKIP
  INTEGER(4)  ::EFDCVER
  INTEGER(4)  ::NBCS,NPBS,NPBW,NPBE,NPBN
  INTEGER :: NQCTL
  INTEGER :: NQCTLSER
  INTEGER :: NQCRULES
  INTEGER :: NQWR
  
  REAL(4)     ::TBEDIT
  
  REAL(4),   ALLOCATABLE ::WVDISP(:,:)
  REAL(4),   ALLOCATABLE ::WVHUU(:,:)
  REAL(4),   ALLOCATABLE ::WVHVV(:,:)
  REAL(4),   ALLOCATABLE ::WVHUV(:,:)

  REAL(4),   ALLOCATABLE ::SAL(:,:)  
  REAL(4),   ALLOCATABLE ::TEM(:,:)  
  REAL(4),   ALLOCATABLE ::SFL(:,:)
  REAL(4),   ALLOCATABLE ::DYE(:,:)  
  REAL(4),   ALLOCATABLE ::HBED(:,:)  
  REAL(4),   ALLOCATABLE ::BDENBED(:,:)  
  REAL(4),   ALLOCATABLE ::PORBED(:,:) 
  REAL(4),   ALLOCATABLE ::CQBEDLOADX(:,:)
  REAL(4),   ALLOCATABLE ::CQBEDLOADY(:,:)  
  REAL(4),   ALLOCATABLE ::TOX(:,:,:)
  REAL(4),   ALLOCATABLE ::TOXB(:,:,:)
  REAL(4),   ALLOCATABLE ::SEDB(:,:,:)  
  REAL(4),   ALLOCATABLE ::VFRBED(:,:,:)  
  REAL(4),   ALLOCATABLE ::SED(:,:,:)
  REAL(4),   ALLOCATABLE ::SNDB(:,:,:)
  REAL(4),   ALLOCATABLE ::SND(:,:,:)  
  REAL(4),   ALLOCATABLE ::WQV(:,:,:)
  REAL(4),   ALLOCATABLE ::WQVA(:,:)
  REAL(4),   ALLOCATABLE ::SEDDIA(:)
  REAL(4),   ALLOCATABLE ::TAUBSED(:)
  REAL(4),   ALLOCATABLE ::TAUBSND(:)
  REAL(4),   ALLOCATABLE ::TAUB(:)
  REAL(4),   ALLOCATABLE ::QQWV1(:)
  REAL(4),   ALLOCATABLE ::WVWHA(:)
  REAL(4),   ALLOCATABLE ::WVFRQL(:)
  REAL(4),   ALLOCATABLE ::WACCWE(:)
  REAL(4),   ALLOCATABLE ::TEMB(:)  
  REAL(4),   ALLOCATABLE ::HJDAY(:)
  REAL(4),   ALLOCATABLE ::SJDAY(:)
  REAL(4),   ALLOCATABLE ::DZCK(:)
  REAL(4),   ALLOCATABLE ::DZCS(:,:)
  
  REAL(4),   ALLOCATABLE ::UA(:)
  REAL(4),   ALLOCATABLE ::VA(:)
  REAL(4),   ALLOCATABLE ::WA(:)
  REAL(4),   ALLOCATABLE ::SALA(:)
  REAL(4),   ALLOCATABLE ::TEMA(:)
  REAL(4),   ALLOCATABLE ::DYEA(:)
  REAL(4),   ALLOCATABLE ::SFLA(:)
  REAL(4),   ALLOCATABLE ::TOXA(:,:)
  REAL(4),   ALLOCATABLE ::SEDA(:,:)
  REAL(4),   ALLOCATABLE ::SNDA(:,:)
  REAL(4),   ALLOCATABLE ::SALZ(:)
  REAL(4),   ALLOCATABLE ::TEMZ(:)
  REAL(4),   ALLOCATABLE ::DYEZ(:)
  REAL(4),   ALLOCATABLE ::TOXZ(:,:)
  REAL(4),   ALLOCATABLE ::SEDZ(:,:)
  REAL(4),   ALLOCATABLE ::SNDZ(:,:)
  REAL(4),   ALLOCATABLE ::UKZ(:)
  REAL(4),   ALLOCATABLE ::VKZ(:)
  REAL(4),   ALLOCATABLE ::WKZ(:)
  REAL(4),   ALLOCATABLE ::WQVZ(:,:) 
  
  REAL(4),   ALLOCATABLE ::WL(:,:)
  REAL(4),   ALLOCATABLE ::QSUM(:,:)
  REAL(4),   ALLOCATABLE ::QSUME(:)
  
  TYPE CELL
    INTEGER(4), ALLOCATABLE:: ICEL(:),JCEL(:)
    REAL(8),    ALLOCATABLE:: XCEL(:)                 
    REAL(8),    ALLOCATABLE:: YCEL(:)  
  END TYPE
  
  CHARACTER(20 )::GEOSYS
  
  ! ** HIGH FREQUENCY OUTPUT
  INTEGER(4) :: HFREOUT,NSUBSET,NPOINT,NGROUP
  TYPE (CELL),   ALLOCATABLE:: HFREGRP(:)
  INTEGER(4),    ALLOCATABLE:: IJHFRE(:),NPNT(:)  
  REAL(4),       ALLOCATABLE:: HFREDAYBG(:),HFREDAYEN(:)
  REAL(4),       ALLOCATABLE:: HFREDUR(:),HFREDAY(:),HFREMIN(:)
  
  ! *** CARD 46A ICE EFFECTS
  INTEGER(4) :: ISICE
  INTEGER(4) :: ISICECOV
  INTEGER(4) :: ISICETHK
  INTEGER(4) :: NISER
  INTEGER(4) :: ICETHKFUN
  INTEGER(4):: ICEFIRST
  INTEGER(4):: ISRHEVAP
  
  REAL(4) ::  DYICEBEG
  REAL(4) ::  DYICEEND
  REAL(4) ::  DYICEM1
  REAL(4) ::  DYICEM2
  REAL(4) ::  RICETHKMAX
  REAL(4) ::  TEMPICE
  REAL(4), ALLOCATABLE :: RICETHKL(:)
  REAL(4), ALLOCATABLE :: RICECOVL(:)
  
  ! *** EVAPORATION
  INTEGER(4)           :: ISGWIE
  INTEGER(4)           :: IEVAP
  REAL(4),ALLOCATABLE  :: EVAPGW(:)
  REAL(4),ALLOCATABLE  :: EVAPSW(:)
  REAL(4),ALLOCATABLE  :: RIFTR(:)
  REAL(4),ALLOCATABLE  :: AGWELV(:)
  
  ! *** LPT
  INTEGER(4)    :: NPD
  INTEGER(4)    :: LPTSNP
  INTEGER(4)    :: XYZSCL
  INTEGER(4)    :: NGRP
  !INTEGER(4)    :: ISSGLFIL
  
  REAL          :: HDRY
  REAL          :: QQMIN
  REAL          :: CTURB2  
  
  REAL(8)       :: TIMESEC
  REAL(8)       :: LA_BEGTI0                 !TIME BEGINNING FOR LAGRA
  REAL(8)       :: LA_ENDTI0                 !TIME ENDING FOR LAGRA
  REAL(RKD)     :: LA_FREQ                   !LA_FREQ IN HOURS FOR LAGRA OUTPUT
  REAL(RKD)     :: TIMEDAY

  REAL,   ALLOCATABLE   :: MOC(:)            ! MASS CONCENTRATION OF OIL [MG/L]
  !REAL,   ALLOCATABLE   :: QQ(:,:)
  REAL,   ALLOCATABLE   :: BEDSHR(:)         ! TAUB/RHO = M2/S2
  REAL,   ALLOCATABLE   :: HP(:)

  REAL(RKD),ALLOCATABLE :: LA_BEGTI(:)
  REAL(RKD),ALLOCATABLE :: LA_ENDTI(:)
  REAL(RKD),ALLOCATABLE :: TAU(:)            !(LCM)
  REAL(RKD),ALLOCATABLE :: XLA(:)            !XLA(NPD) DRIFTER COORDINATES
  REAL(RKD),ALLOCATABLE :: YLA(:)            !YLA(NPD)
  REAL(RKD),ALLOCATABLE :: ZLA(:)            !ZLA(NPD)
  REAL(RKD),ALLOCATABLE :: DVOL(:)           !(1:NPD ) VOLUME OF EACH OIL DRIFTER [M3]
  REAL(RKD),ALLOCATABLE :: LPTTIME(:)
  REAL(RKD),ALLOCATABLE :: DDEN(:)           !(1:NGRP) DENSITY OF OIL SPILL OF EACH GROUP[KG/M3]
  
  INTEGER,  ALLOCATABLE :: LLA(:)            !LIJ(NP) INDEX OF POLYGON
  INTEGER,  ALLOCATABLE :: ISOILSPI(:)       !(1:NGRP), 0: NORMAL DRIFTER/1:OIL DRIFTER
  INTEGER,  ALLOCATABLE :: LA_GRP(:)
 
    
END MODULE
