SUBROUTINE BUDGET1

  ! **  ADDED BY DON KINGERY, CH2M-HILL ON 15 OCTOBER 1996
  ! CHANGE RECORD
  ! **  SUBROUTINES BUDGETN CALCULATE SEDIMENT BUDGET (TOTAL SEDIMENTS)

  USE GLOBAL
  IMPLICIT NONE
  INTEGER :: K,L,NS
  IF( NBUD > 1) RETURN

  ! **  INITIALIZE VOLUME, SALT MASS, SEDIMENT, AND ASSOCIATED FLUXES
  VOLMBEG=0.
  SMASSBEG=0.
  BSEDBEG=0.
  SSEDBEG=0.
  SEDIN=0.
  SEDOUT=0.
  VOLMOUT=0.
  SMASSOUT=0.
  VOLMIN=0.
  SMASSIN=0.
  DO K=1,KB
    DO L=2,LA
      SEDBT(L,K)=0.
      SNDBT(L,K)=0.
    ENDDO
  ENDDO
  IF( N <= 1 )THEN
    DO NS=1,NSED
      DO K=1,KB
        DO L=2,LA
          SEDBT(L,K)=SEDBT(L,K)+SEDB1(L,K,NS)
        ENDDO
      ENDDO
    ENDDO
    DO NS=1,NSND
      DO K=1,KB
        DO L=2,LA
          SNDBT(L,K)=SNDBT(L,K)+SNDB1(L,K,NS)
        ENDDO
      ENDDO
    ENDDO
  ENDIF
  IF( N > 1 )THEN
    DO NS=1,NSED
      DO K=1,KB
        DO L=2,LA
          SEDBT(L,K)=SEDBT(L,K)+SEDB(L,K,NS)
        ENDDO
      ENDDO
    ENDDO
    DO NS=1,NSND
      DO K=1,KB
        DO L=2,LA
          SNDBT(L,K)=SNDBT(L,K)+SNDB(L,K,NS)
        ENDDO
      ENDDO
    ENDDO
  ENDIF

  !!VOLBW3 IS TO ACCUMULATE WC-SEDBED FLUX
  DO K=1,KB
    DO L=2,LA
      VOLBW3(L,K)=0.
      BSEDBEG=BSEDBEG+SCB(L)*DXYP(L)*(SEDBT(L,K)+SNDBT(L,K))
    ENDDO
  ENDDO
  IF( N <= 1 )THEN
    DO NS=1,NSED
      DO K=1,KC
        DO L=2,LA
          SSEDBEG=SSEDBEG+SCB(L)*DXYP(L)*H1P(L)*SED1(L,K,NS)*DZC(L,K)
        ENDDO
      ENDDO
    ENDDO
    DO NS=1,NSND
      DO K=1,KC
        DO L=2,LA
          SSEDBEG=SSEDBEG+SCB(L)*DXYP(L)*H1P(L)*SND1(L,K,NS)*DZC(L,K)
        ENDDO
      ENDDO
    ENDDO
  ENDIF
  IF( N > 1 )THEN
    DO NS=1,NSED
      DO K=1,KC
        DO L=2,LA
          SSEDBEG=SSEDBEG+SCB(L)*DXYP(L)*HP(L)*SED(L,K,NS)*DZC(L,K)
        ENDDO
      ENDDO
    ENDDO
    DO NS=1,NSND
      DO K=1,KC
        DO L=2,LA
          SSEDBEG=SSEDBEG+SCB(L)*DXYP(L)*HP(L)*SND(L,K,NS)*DZC(L,K)
        ENDDO
      ENDDO
    ENDDO
  ENDIF
  SEDBEG=BSEDBEG+SSEDBEG
  IF( N <= 1 )THEN
    DO L=2,LA
      VOLMBEG=VOLMBEG+SPB(L)*DXYP(L)*H1P(L)
    ENDDO
    DO K=1,KC
      DO L=2,LA
        SMASSBEG=SMASSBEG+SCB(L)*DXYP(L)*H1P(L)*SAL1(L,K)*DZC(L,K)
      ENDDO
    ENDDO
  ENDIF
  IF( N > 1 )THEN
    DO L=2,LA
      VOLMBEG=VOLMBEG+SPB(L)*DXYP(L)*HP(L)
    ENDDO
    DO K=1,KC
      DO L=2,LA
        SMASSBEG=SMASSBEG+SCB(L)*DXYP(L)*HP(L)*SAL(L,K)*DZC(L,K)
      ENDDO
    ENDDO
  ENDIF
  RETURN
END

SUBROUTINE BUDGET2

  ! **  ADDED BY DON KINGERY, CH2M-HILL ON 15 OCTOBER 1996
  ! CHANGE RECORD
  ! **  SUBROUTINES BUDGETN CALCULATE SEDIMENT BUDGET (TOTAL SEDIMENTS)

  USE GLOBAL
  IMPLICIT NONE
  INTEGER :: LS,NT,LL,K,L,LN

  ! **  ACCUMULATE FLUXES ACROSS OPEN BOUNDARIES
  DO K=1,KC
    DO LL=1,NCBS
      L=LCBS(LL)
      LN=LNC(L)
      VOLMOUT=VOLMOUT-VHDX2(LN,K)
      SMASSOUT=SMASSOUT-MIN(VHDX2(LN,K),0.)*SAL1(LN,K)-MAX(VHDX2(LN,K),0.)*SAL1(L,K)

      !  ADDED SEDIMENT FLUXES         DLK 9/27
      DO NT=1,NSED
        SEDOUT=SEDOUT-MIN(VHDX2(LN,K),0.)*SED1(LN,K,NT)-MAX(VHDX2(LN,K),0.)*SED1(L,K,NT)
      ENDDO
      DO NT=1,NSND
        SEDOUT=SEDOUT-MIN(VHDX2(LN,K),0.)*SND1(LN,K,NT)-MAX(VHDX2(LN,K),0.)*SND1(L,K,NT)
      ENDDO
    ENDDO
  ENDDO
  DO K=1,KC
    DO LL=1,NCBW
      L=LCBW(LL)
      VOLMOUT=VOLMOUT-UHDY2(LEC(L),K)
      SMASSOUT=SMASSOUT-MIN(UHDY2(LEC(L),K),0.)*SAL1(LEC(L),K)-MAX(UHDY2(LEC(L),K),0.)*SAL1(L,K)

      !  ADDED SEDIMENT FLUXES         DLK 10/15
      DO NT=1,NSED
        SEDOUT=SEDOUT-MIN(UHDY2(LEC(L),K),0.)*SED1(LEC(L),K,NT)-MAX(UHDY2(LEC(L),K),0.)*SED1(L,K,NT)
      ENDDO
      DO NT=1,NSND
        SEDOUT=SEDOUT-MIN(UHDY2(LEC(L),K),0.)*SND1(LEC(L),K,NT)-MAX(UHDY2(LEC(L),K),0.)*SND1(L,K,NT)
      ENDDO
    ENDDO
  ENDDO
  DO K=1,KC
    DO LL=1,NCBE
      L=LCBE(LL)
      VOLMOUT=VOLMOUT+UHDY2(L,K)
      SMASSOUT=SMASSOUT+MIN(UHDY2(L,K),0.)*SAL1(L,K)+MAX(UHDY2(L,K),0.)*SAL1(LWC(L),K)

      !  ADDED SEDIMENT FLUXES         DLK 10/15
      DO NT=1,NSED
        SEDOUT=SEDOUT+MIN(UHDY2(L,K),0.)*SED1(L,K,NT)+MAX(UHDY2(L,K),0.)*SED1(LWC(L),K,NT)
      ENDDO
      DO NT=1,NSND
        SEDOUT=SEDOUT+MIN(UHDY2(L,K),0.)*SND1(L,K,NT)+MAX(UHDY2(L,K),0.)*SND1(LWC(L),K,NT)
      ENDDO
    ENDDO
  ENDDO
  DO K=1,KC
    DO LL=1,NCBN
      L=LCBN(LL)
      LS=LSC(L)
      VOLMOUT=VOLMOUT+VHDX2(L,K)
      SMASSOUT=SMASSOUT+MIN(VHDX2(L,K),0.)*SAL1(L,K)+MAX(VHDX2(L,K),0.)*SAL1(LS,K)

      !  ADDED SEDIMENT FLUXES         DLK 10/15
      DO NT=1,NSED
        SEDOUT=SEDOUT+MIN(VHDX2(L,K),0.)*SED1(L,K,NT)+MAX(VHDX2(L,K),0.)*SED1(LS,K,NT)
      ENDDO
      DO NT=1,NSND
        SEDOUT=SEDOUT+MIN(VHDX2(L,K),0.)*SND1(L,K,NT)+MAX(VHDX2(L,K),0.)*SND1(LS,K,NT)
      ENDDO
    ENDDO
  ENDDO

  ! **  ACCUMULATE FLUX OF SED POSITIVE FROM BED TO WATER COLUMN

  RETURN
END

SUBROUTINE BUDGET3

  ! **  ADDED BY DON KINGERY, CH2M-HILL ON 15 OCTOBER 1996
  ! CHANGE RECORD
  ! **  SUBROUTINES BUDGETN CALCULATE SEDIMENT BUDGET (TOTAL SEDIMENTS)

  USE GLOBAL

  IMPLICIT NONE                                                                                                          
                                                                                                                         
  INTEGER :: K,L,NS,NWR,NCTL,ID,JD,LD,KU,KD,M,IU,JU,LU,NN                                                                
  INTEGER :: NQSTMP,NCSTMP                                                                                               
  REAL   :: RQWD,VOLCONT,VOLMAST,QWRABS                                                                                 

  ! **  ACCUMULATE INTERNAL SOURCES AND SINKS                                                                             
  VOLCONT=0.
  VOLMAST=0.
  DO L=2,LA
    VOLMIN=VOLMIN+QSUME(L)
    VOLCONT=VOLCONT+QSUME(L)
  ENDDO
  IF( ISTRAN(1) >= 1 )THEN
    DO K=1,KC
      DO L=2,LC
        CONT(L,K)=SAL1(L,K)
      ENDDO
    ENDDO
    DO NS=1,NQSIJ
      L=LQS(NS)
      NQSTMP=NQSERQ(NS)
      NCSTMP=NCSERQ(NS,1)
      DO K=1,KC
        SMASSIN=SMASSIN+MAX(QSS(K,NS),0.)*CQS(K,NS,1)+MIN(QSS(K,NS),0.)*SAL1(L,K)+MAX(QSERCELL(K,NS),0.)*CSERT(K,NCSTMP,1)+MIN(QSERCELL(K,NS),0.)*SAL1(L,K)
      ENDDO
    ENDDO
    DO NCTL=1,NQCTL
      RQWD=1.
      IU=IQCTLU(NCTL)
      JU=JQCTLU(NCTL)
      LU=LIJ(IU,JU)
      ID=IQCTLD(NCTL)
      JD=JQCTLD(NCTL)
      IF( ID == 0 .AND. JD == 0 )THEN
        LD=LC
        RQWD=0.
      ELSE
        LD=LIJ(ID,JD)
      ENDIF
      DO K=1,KC
        SMASSIN=SMASSIN+QCTLT(K,NCTL,1)*CONT(LU,K)-RQWD*QCTLT(K,NCTL,1)*CONT(LU,K)
      ENDDO
    ENDDO
    DO NWR=1,NQWR
      NQSTMP=NQWRSERQ(NWR)
      NCSTMP=NQWRSERQ(NWR)
      ! *** Handle +/- Flows for Withdrawal/Return Structures
      IF( QWRSERT(NQSTMP) >= 0. )THEN
        ! *** Original Withdrawal/Return
        IU=IQWRU(NWR)
        JU=JQWRU(NWR)
        KU=KQWRU(NWR)
        ID=IQWRD(NWR)
        JD=JQWRD(NWR)
        KD=KQWRD(NWR)
      ELSE
        ! *** Reverse Flow Withdrawal/Return
        ID=IQWRU(NWR)
        JD=JQWRU(NWR)
        KD=KQWRU(NWR)
        IU=IQWRD(NWR)
        JU=JQWRD(NWR)
        KU=KQWRD(NWR)
      ENDIF
      QWRABS = ABS(QWRSERT(NQSTMP))
      LU=LIJ(IU,JU)
      LD=LIJ(ID,JD)

      SMASSIN=SMASSIN+( (QWR(NWR)+QWRABS)*CONT(LU,KU) )
      IF( LD /= 1 .OR. LD /= LC )THEN
        SMASSIN=SMASSIN-( QWR(NWR)*(CONT(LU,KU)+CQWR(NWR,1))+QWRABS*(CONT(LU,KU)+CQWRSERT(NCSTMP,1)) )
      ENDIF
    ENDDO
  ENDIF

  !    ACCUMULATE INTERNAL SOURCES AND SINKS FOR SED   (DLK 10/15)
  IF( ISTRAN(6) >= 1 )THEN
    DO NN=1,NSED
      M=MSVSED(NN)
      DO K=1,KC
        DO L=2,LC
          CONT(L,K)=SED(L,K,NN)
        ENDDO
      ENDDO
      DO NS=1,NQSIJ
        L=LQS(NS)
        NQSTMP=NQSERQ(NS)
        NCSTMP=NCSERQ(NS,M)
        DO K=1,KC
          SEDIN=SEDIN+MAX(QSS(K,NS),0.)*CQS(K,NS,M)+MIN(QSS(K,NS),0.)*SED1(L,K,NN)+MAX(QSERCELL(K,NS),0.)*CSERT(K,NCSTMP,M)+MIN(QSERCELL(K,NS),0.)*SED1(L,K,NN)
          IF( NN == 1 ) VOLMAST=VOLMAST+QSERCELL(K,NS)+QSS(K,NS)
        ENDDO
      ENDDO
      DO NCTL=1,NQCTL
        RQWD=1.
        IU=IQCTLU(NCTL)
        JU=JQCTLU(NCTL)
        LU=LIJ(IU,JU)
        ID=IQCTLD(NCTL)
        JD=JQCTLD(NCTL)
        IF( ID == 0 .AND. JD == 0 )THEN
          LD=LC
          RQWD=0.
        ELSE
          LD=LIJ(ID,JD)
        ENDIF
        DO K=1,KC
          SEDIN=SEDIN+QCTLT(K,NCTL,1)*CONT(LU,K)-RQWD*QCTLT(K,NCTL,1)*CONT(LU,K)
        ENDDO
      ENDDO
      DO NWR=1,NQWR
        NQSTMP=NQWRSERQ(NWR)
        NCSTMP=NQWRSERQ(NWR)
        ! *** Handle +/- Flows for Withdrawal/Return Structures
        IF( QWRSERT(NQSTMP) >= 0. )THEN
          ! *** Original Withdrawal/Return
          IU=IQWRU(NWR)
          JU=JQWRU(NWR)
          KU=KQWRU(NWR)
          ID=IQWRD(NWR)
          JD=JQWRD(NWR)
          KD=KQWRD(NWR)
        ELSE
          ! *** Reverse Flow Withdrawal/Return
          ID=IQWRU(NWR)
          JD=JQWRU(NWR)
          KD=KQWRU(NWR)
          IU=IQWRD(NWR)
          JU=JQWRD(NWR)
          KU=KQWRD(NWR)
        ENDIF
        QWRABS = ABS(QWRSERT(NQSTMP))
        LU=LIJ(IU,JU)
        LD=LIJ(ID,JD)

        SEDIN=SEDIN+( (QWR(NWR)+QWRABS)*CONT(LU,KU) )
        IF( LD /= 1 .OR. LD /= LC )THEN
          SEDIN=SEDIN-( QWR(NWR)*(CONT(LU,KU)+CQWR(NWR,M))+QWRABS*(CONT(LU,KU)+CQWRSERT(NCSTMP,M)) )
        ENDIF
      ENDDO
    ENDDO
  ENDIF

  !    ACCUMULATE INTERNAL SOURCES AND SINKS FOR SND   (DLK 10/15)
  IF( ISTRAN(7) >= 1 )THEN
    DO NN=1,NSND
      M=MSVSND(NN)
      DO K=1,KC
        DO L=2,LC
          CONT(L,K)=SND(L,K,NN)
        ENDDO
      ENDDO
      DO NS=1,NQSIJ
        L=LQS(NS)
        NQSTMP=NQSERQ(NS)
        NCSTMP=NCSERQ(NS,M)
        DO K=1,KC
          SEDIN=SEDIN+MAX(QSS(K,NS),0.)*CQS(K,NS,M)+MIN(QSS(K,NS),0.)*SND1(L,K,NN)+MAX(QSERCELL(K,NS),0.)*CSERT(K,NCSTMP,M)+MIN(QSERCELL(K,NS),0.)*SND1(L,K,NN)
        ENDDO
      ENDDO
      DO NCTL=1,NQCTL
        RQWD=1.
        IU=IQCTLU(NCTL)
        JU=JQCTLU(NCTL)
        LU=LIJ(IU,JU)
        ID=IQCTLD(NCTL)
        JD=JQCTLD(NCTL)
        IF( ID == 0 .AND. JD == 0 )THEN
          LD=LC
          RQWD=0.
        ELSE
          LD=LIJ(ID,JD)
        ENDIF
        DO K=1,KC
          SEDIN=SEDIN+QCTLT(K,NCTL,1)*CONT(LU,K)-RQWD*QCTLT(K,NCTL,1)*CONT(LU,K)
        ENDDO
      ENDDO
      DO NWR=1,NQWR
        NQSTMP=NQWRSERQ(NWR)
        NCSTMP=NQWRSERQ(NWR)
        ! *** Handle +/- Flows for Withdrawal/Return Structures
        IF( QWRSERT(NQSTMP) >= 0. )THEN
          ! *** Original Withdrawal/Return
          IU=IQWRU(NWR)
          JU=JQWRU(NWR)
          KU=KQWRU(NWR)
          ID=IQWRD(NWR)
          JD=JQWRD(NWR)
          KD=KQWRD(NWR)
        ELSE
          ! *** Reverse Flow Withdrawal/Return
          ID=IQWRU(NWR)
          JD=JQWRU(NWR)
          KD=KQWRU(NWR)
          IU=IQWRD(NWR)
          JU=JQWRD(NWR)
          KU=KQWRD(NWR)
        ENDIF
        QWRABS = ABS(QWRSERT(NQSTMP))
        LU=LIJ(IU,JU)
        LD=LIJ(ID,JD)

        SEDIN=SEDIN+( (QWR(NWR)+QWRABS)*CONT(LU,KU) )
        IF( LD /= 1 .OR. LD /= LC )THEN
          SEDIN=SEDIN-( QWR(NWR)*(CONT(LU,KU)+CQWR(NWR,M))+QWRABS*(CONT(LU,KU)+CQWRSERT(NCSTMP,M)) )
        ENDIF
      ENDDO
    ENDDO
  ENDIF
    600 FORMAT(' VOLCON,VOLMAS = ',2E14.6)
  RETURN
END

SUBROUTINE BUDGET5

  ! **  ADDED BY DON KINGERY, CH2M-HILL ON 15 OCTOBER 1996
  ! CHANGE RECORD
  ! **  SUBROUTINES BUDGETN CALCULATE SEDIMENT BUDGET (TOTAL SEDIMENTS)

  USE GLOBAL
  IMPLICIT NONE
  INTEGER :: NS,L,K
  REAL :: SEDBTMP1,SEDBTMP,SFLXTMP,BSEDERR,SSEDOUT,BSEDOUT,SSEDERE
  REAL :: BSEDERE,SSEDBMO,BSEDBMO,SSEDERR,SDFLUX,VOLMBMO
  REAL :: SMASSBMO,VOLMERR,SMASSERR
  !
  ! **  CHECK FOR END OF BALANCE PERIOD
  !
  IF( NBUD == NTSMMT )THEN
   6666 FORMAT(' ACTIVE CALL TO BUDGET5, N,NBUD = ',2I5)

    ! **  CALCULATE ENDING SUSPENDED AND BOTTOM SEDIMENT IN THE MODEL DOMAIN
    SDFLUX=0.
    SSEDEND=0.
    BSEDEND=0.
    VOLMEND=0.
    SMASSEND=0.
    IF( N == NTSMMT )THEN
      DO L=2,LA
        VOLMEND=VOLMEND+SPB(L)*DXYP(L)*H1P(L)
      ENDDO
    ELSE
      DO L=2,LA
        VOLMEND=VOLMEND+SPB(L)*DXYP(L)*HP(L)
      ENDDO
    ENDIF
    IF( N == NTSMMT )THEN
      DO K=1,KC
        DO L=2,LA
          SMASSEND=SMASSEND+SCB(L)*DXYP(L)*H1P(L)*SAL1(L,K)*DZC(L,K)
        ENDDO
      ENDDO
    ELSE
      DO K=1,KC
        DO L=2,LA
          SMASSEND=SMASSEND+SCB(L)*DXYP(L)*HP(L)*SAL(L,K)*DZC(L,K)
        ENDDO
      ENDDO
    ENDIF

    !  INITIALIZE BOTTOM AND SUSPENDED SEDIMENT MASS  ---  DLK 9/26
    DO L=2,LA
      SDFLUX=SDFLUX+SCB(L)*VOLBW3(L,KB)
    ENDDO
    DO K=1,KB
      DO L=2,LA
        SEDBT(L,K)=0.
        SNDBT(L,K)=0.
      ENDDO
    ENDDO
    IF( N == NTSMMT )THEN
      DO NS=1,NSED
        DO K=1,KB
          DO L=2,LA
            SEDBT(L,K)=SEDBT(L,K)+SCB(L)*SEDB1(L,K,NS)
          ENDDO
        ENDDO
      ENDDO
      DO NS=1,NSND
        DO K=1,KB
          DO L=2,LA
            SNDBT(L,K)=SNDBT(L,K)+SCB(L)*SNDB1(L,K,NS)
          ENDDO
        ENDDO
      ENDDO
    ELSE
      DO NS=1,NSED
        DO K=1,KB
          DO L=2,LA
            SEDBT(L,K)=SEDBT(L,K)+SCB(L)*SEDB(L,K,NS)
          ENDDO
        ENDDO
      ENDDO
      DO K=1,KB
        DO NS=1,NSND
          DO L=2,LA
            SNDBT(L,K)=SNDBT(L,K)+SCB(L)*SNDB(L,K,NS)
          ENDDO
        ENDDO
      ENDDO
    ENDIF
    DO K=1,KB
      DO L=2,LA
        BSEDEND=BSEDEND+SCB(L)*DXYP(L)*(SEDBT(L,K)+SNDBT(L,K))
      ENDDO
    ENDDO
    IF( N == NTSMMT )THEN
      DO NS=1,NSED
        DO K=1,KC
          DO L=2,LA
           SSEDEND=SSEDEND+SCB(L)*DXYP(L)*H1P(L)*SED1(L,K,NS)*DZC(L,K)
          ENDDO
        ENDDO
      ENDDO
      DO NS=1,NSND
        DO K=1,KC
          DO L=2,LA
           SSEDEND=SSEDEND+SCB(L)*DXYP(L)*H1P(L)*SND1(L,K,NS)*DZC(L,K)
          ENDDO
        ENDDO
      ENDDO
    ELSE
      DO NS=1,NSED
        DO K=1,KC
          DO L=2,LA
            SSEDEND=SSEDEND+SCB(L)*DXYP(L)*HP(L)*SED(L,K,NS)*DZC(L,K)
          ENDDO
        ENDDO
      ENDDO
      DO NS=1,NSND
        DO K=1,KC
          DO L=2,LA
            SSEDEND=SSEDEND+SCB(L)*DXYP(L)*HP(L)*SND(L,K,NS)*DZC(L,K)
          ENDDO
        ENDDO
      ENDDO
    ENDIF
    SEDEND=SSEDEND+BSEDEND
    SEDOUT=DT*SEDOUT
    SEDIN=DT*SEDIN
    VOLMOUT=DT*VOLMOUT
    VOLMIN=DT*VOLMIN
    SMASSIN=DT*SMASSIN
    SMASSOUT=DT*SMASSOUT
    SDFLUX=DT*SDFLUX
    SEDBMO=SEDBEG+SEDIN-SEDOUT
    VOLMBMO=VOLMBEG+VOLMIN-VOLMOUT
    SMASSBMO=SMASSBEG+SMASSIN-SMASSOUT
    SEDERR=SEDEND-SEDBMO
    VOLMERR=VOLMEND-VOLMBMO
    SMASSERR=SMASSEND-SMASSBMO
    RSDERDE=-9999.
    RSDERDO=-9999.
    IF( SEDEND /= 0. ) RSDERDE=SEDERR/SEDEND
    IF( SEDOUT /= 0. ) RSDERDO=SEDERR/(SEDIN+SEDOUT)

    ! **  OUTPUT BALANCE RESULTS TO FILE BUDGET.OUT
    IF( JSSBAL == 1 )THEN
      OPEN(89,FILE=OUTDIR//'BUDGET.OUT',STATUS='UNKNOWN')
      OPEN(93,FILE=OUTDIR//'BUDGET2.OUT',STATUS='UNKNOWN')
      OPEN(94,FILE=OUTDIR//'BUDGET3.OUT',STATUS='UNKNOWN')
      CLOSE(89,STATUS='DELETE')
      CLOSE(93,STATUS='DELETE')
      CLOSE(94,STATUS='DELETE')
      OPEN(89,FILE=OUTDIR//'BUDGET.OUT',STATUS='UNKNOWN')
      WRITE(89,888)NTSMMT,TBEGIN
      OPEN(93,FILE=OUTDIR//'BUDGET2.OUT',STATUS='UNKNOWN')
      WRITE(93,893)NTSMMT,TBEGIN
      OPEN(94,FILE=OUTDIR//'BUDGET3.OUT',STATUS='UNKNOWN')
      WRITE(94,894)NTSMMT,TBEGIN
      JSSBAL=0
    ELSE
      OPEN(89,FILE=OUTDIR//'BUDGET.OUT',POSITION='APPEND',STATUS='UNKNOWN')
      OPEN(93,FILE=OUTDIR//'BUDGET2.OUT',POSITION='APPEND',STATUS='UNKNOWN')
      OPEN(94,FILE=OUTDIR//'BUDGET3.OUT',POSITION='APPEND',STATUS='UNKNOWN')
    ENDIF
    WRITE(89,892)N,BSEDBEG,SSEDBEG,SEDIN,SEDOUT,SEDBMO,BSEDEND,SSEDEND,SEDERR,RSDERDE,RSDERDO
    WRITE(93,895)N,VOLMBEG,VOLMIN,VOLMOUT,VOLMBMO,VOLMEND,VOLMERR
    WRITE(94,895)N,SMASSBEG,SMASSIN,SMASSOUT,SMASSBMO,SMASSEND,SMASSERR
    SSEDBMO=SSEDBEG+SEDIN-SEDOUT+SDFLUX
    BSEDBMO=BSEDBEG-SDFLUX
    SSEDERR=SSEDEND-SSEDBMO
    BSEDERR=BSEDEND-BSEDBMO
    SSEDOUT=SEDOUT-SEDIN-SDFLUX
    BSEDOUT=SDFLUX
    SSEDBMO=SSEDBEG-SSEDOUT
    BSEDBMO=BSEDBEG-BSEDOUT
    SSEDERR=SSEDEND-SSEDBMO
    BSEDERR=BSEDEND-BSEDBMO
    IF( SSEDEND /= 0. )SSEDERE=SSEDERR/SSEDEND
    IF( BSEDEND /= 0. )BSEDERE=BSEDERR/BSEDEND
    DO L=2,LA
      VOLBW3(L,KB)=DT*VOLBW3(L,KB)
      SEDBTMP1=DXYP(L)*SEDB1(L,KBT(L),1)
      SEDBTMP=DXYP(L)*SEDB(L,KB,1)
      SFLXTMP=DT*DXYP(L)*SEDF(L,0,1)
    ENDDO
    CLOSE(89)
    CLOSE(93)
    CLOSE(94)
   9510 FORMAT(//' SUS AND BED SED BUDGET ENDING AT N =',I7/)
   9511 FORMAT(' SEDIN,SEDOUT,SDFLUX = ',3E15.7/)
   9512 FORMAT(' SSEDBEG,BSEDBEG = ',2E15.7/)
   9513 FORMAT(' SSEDOUT,BSEDOUT = ',2E15.7/)
   9514 FORMAT(' SSEDBMO,BSEDBMO = ',2E15.7/)
   9515 FORMAT(' SSEDEND,BSEDEND = ',2E15.7/)
   9516 FORMAT(' SSEDERR,BSEDERR = ',2E15.7/)
   9517 FORMAT(' SSEDERE,BSEDERE = ',2E15.7/)
   9600 FORMAT(/'C ACCUMULATED SED FLUX AT N = ',I5)
   9601 FORMAT(2I5,5E15.7)
    888 FORMAT (6X,' SEDIMENT BUDGET CALCULATIONS'//6X,'SEDIMENT BUDGET OVER ',I5,' TIME STEPS'/ &
      6X,'STARTING ON JULIAN DAY ',F8.2/ &
      6X,'N       = LAST TIME STEP IN PERIOD'/ &
      6X,'BSEDBEG  = TOTAL BED SEDIMENT IN MODEL DOMAIN &
      AT BEGINNING',' OF TIME PERIOD'/ &
      6X,'SSEDBEG  = TOTAL SUSPENDED SEDIMENT IN MODEL DOMAIN AT', &
      ' BEGINNING OF TIME PERIOD'/ &
      6X,'SEDIN   = SEDIMENT ADDED TO MODEL FROM OUTFALL'/ &
      6X,'SEDOUT  = SEDIMENT REMOVED ACROSS MODEL BOUNDARIES'/ &
      6X,'SEDBMO  = SEDBEG+SEDIN-SEDOUT'/ &
      6X,'SEDEND  = SEDIMENT REMAINING IN MODEL DOMAIN'/ &
      6X,'SEDERR  = SEDEND-SEDBMO'/ &
      6X,'RSDERDE = ERROR AS A FRACTION OF SEDIMENT IN MODEL DOMAIN'/ &
      6X,'RSDERDO = ERROR AS A FRACTION OF SEDIMENT ADDED/REMOVED'//  &
      1X,'       N         BSEDBEG SSEDBEG        SEDIN', &
      1X,'          SEDOUT          SEDBMO                &
    ',1X,'    BSEDEND          SSEDEND          SEDERR  RSDERDE',1X,'         RSDERDO'/)
    892 FORMAT (1X,I9,10(2X,E14.6))
    893 FORMAT (6X,' MASS BALANCE CALCULATIONS'// &
      6X,'MASS BALANCE OVER ',I10,' TIME STEPS'/ &
      6X,'STARTING ON JULIAN DAY ',F9.2/ &
      6X,'N       = LAST TIME STEP IN PERIOD'/ &
      6X,'VOLMBEG = TOTAL WATER VOLUME IN MODEL DOMAIN &
      AT BEGINNING',' OF TIME PERIOD'/ &
      6X,'VOLMIN  = WATER VOLUME ADDED TO MODEL FROM INFLOWS'/ &
      6X,'VOLMOUT = WATER VOLUME REMOVED ACROSS MODEL BOUNDARIES'/ &
      6X,'VOLMBMO = VOLMBEG-(VOLMIN+VOLMOUT)'/ &
      6X,'VOLMEND = WATER VOLUME REMAINING IN MODEL DOMAIN'/ &
      6X,'VOLMERR = VOLMEND-VOLMBMO'// &
      1X,'       N         VOLMBEG        VOLMIN         VOLMOUT', &
      1X,'        VOLMBMO        VOLMEND          VOLMERR'/)
    894 FORMAT (6X,' SALT BALANCE CALCULATIONS'// &
      6X,'SALT BALANCE OVER ',I10,' TIME STEPS'/ &
      6X,'STARTING ON JULIAN DAY ',F9.2/ &
      6X,'N        = LAST TIME STEP IN PERIOD'/ &
      6X,'SMASSBEG = TOTAL WATER VOLUME IN MODEL DOMAIN &
      AT BEGINNING',' OF TIME PERIOD'/ &
      6X,'SMASSIN  = WATER VOLUME ADDED TO MODEL FROM INFLOWS'/ &
      6X,'SMASSOUT = WATER VOLUME REMOVED ACROSS MODEL BOUNDARIES'/ &
      6X,'SMASSBMO = VOLMBEG-(VOLMIN+VOLMOUT)'/ &
      6X,'SMASSEND = WATER VOLUME REMAINING IN MODEL DOMAIN'/ &
      6X,'SMASSERR = VOLMEND-VOLMBMO'// &
      1X,'       N        SMASSBEG       SMASSIN        SMASSOUT', &
      1X,'       SMASSBMO       SMASSEND         SMASSERR'/)
    895 FORMAT (1X,I9,6(2X,E14.6))
    NBUD=0
  ENDIF
  NBUD=NBUD+1
  RETURN
END

