SUBROUTINE CELLMAP

  ! **  SUBROUTINE CELLMAP GENERATES CELL MAPPINGS
  ! CHANGE RECORD

  USE GLOBAL
  USE INFOMOD,ONLY:READSTR
  IMPLICIT NONE
  INTEGER :: L,I,J,LCTT,NPN,LE,LW,LS,LN,NW,IGTMP,JGTMP,ICOMP,JCOMP,LTMP
  CHARACTER(200) :: STR
  
  ! **  SET 1D CELL INDEX SEQUENCE AND MAPPINGS
  L=2
  DO J=1,JC
    DO I=1,IC
      IF( IJCT(I,J) > 0 .AND. IJCT(I,J) < 9 )THEN
        IL(L)=I
        JL(L)=J
        LCT(L)=IJCT(I,J)
        LIJ(I,J)=L
        L=L+1
      ENDIF
    ENDDO
  ENDDO

  LA=L-1
  LCTT=L
  IF( LCTT /= LC )THEN
    WRITE(6,1617)LCTT,LC
    WRITE(7,1617)LCTT,LC
    WRITE(8,1617)LCTT,LC
    STOP
  ENDIF
  IL(1)=0
  IL(LC)=0
  JL(1)=0
  JL(LC)=0

  WRITE(7,601)LA
  WRITE(8,601)LA

    601 FORMAT('  LA=',I10,//)
   1616 FORMAT(2I10)
   1617 FORMAT(' LC =',I5,' DETERMINED IN CELLMAP',' INCONSITENT WITH INPUT VALUE =',I5//)

  IF( ISWASP <= 5 )THEN
    L=2
    DO J=1,JC
      DO I=1,IC
        IF( IJCTLT(I,J) > 0 .AND. IJCTLT(I,J) < 9 )THEN
          ILLT(L)=I
          JLLT(L)=J
          LCTLT(L)=IJCTLT(I,J)
          LIJLT(I,J)=L
          L=L+1
        ENDIF
      ENDDO
    ENDDO
    LALT=L-1
    LCLT=L
  ENDIF
  
  IF( ISWASP >= 6 )THEN
    L=2
    DO J=1,JC
      DO I=1,IC
        IF( IJCTLT(I,J) > 0 .AND. IJCTLT(I,J) < 7 )THEN
          ILLT(L)=I
          JLLT(L)=J
          LCTLT(L)=IJCTLT(I,J)
          LIJLT(I,J)=L
          L=L+1
        ENDIF
      ENDDO
    ENDDO
    LALT=L-1
    LCLT=L
  ENDIF
  WRITE(7,1616)LALT,LCLT
  WRITE(8,1616)LALT,LCLT

  ! **  SET NORTH AND SOUTH CELL IDENTIFIER ARRAYS
  LNC(1)=LC
  LSC(1)=LC
  LNEC(1)=LC
  LNWC(1)=LC
  LSEC(1)=LC
  LSWC(1)=LC
  LNC(LC)=1
  LSC(LC)=1
  LNEC(LC)=1
  LNWC(LC)=1
  LSEC(LC)=1
  LSWC(LC)=1
  DO L=2,LA
    I=IL(L)
    J=JL(L)
    IF( IJCT(I,J+1) == 9 )THEN
      LNC(L)=LC
    ELSE
      LNC(L)=LIJ(I,J+1)
    ENDIF
    IF( IJCT(I,J-1) == 9 )THEN
      LSC(L)=LC
    ELSE
      LSC(L)=LIJ(I,J-1)
    ENDIF
    IF( IJCT(I+1,J+1) == 9 )THEN
      LNEC(L)=LC
    ELSE
      LNEC(L)=LIJ(I+1,J+1)
    ENDIF
    IF( IJCT(I-1,J+1) == 9 )THEN
      LNWC(L)=LC
    ELSE
      LNWC(L)=LIJ(I-1,J+1)
    ENDIF
    IF( IJCT(I+1,J-1) == 9 )THEN
      LSEC(L)=LC
    ELSE
      LSEC(L)=LIJ(I+1,J-1)
    ENDIF
    IF( IJCT(I-1,J-1) == 9 )THEN
      LSWC(L)=LC
    ELSE
      LSWC(L)=LIJ(I-1,J-1)
    ENDIF
  ENDDO

  ! *** CONNECT EAST-WEST CELLS
  LEC(1)=LC
  LWC(1)=LC
  LEC(LC)=1
  LWC(LC)=1
  DO L=2,LA
    I=IL(L)
    J=JL(L)
    IF( IJCT(I+1,J) == 9 )THEN
      LEC(L)=LC
    ELSE
      LEC(L)=LIJ(I+1,J)
    ENDIF
    IF( IJCT(I-1,J) == 9 )THEN
      LWC(L)=LC
    ELSE
      LWC(L)=LIJ(I-1,J)
    ENDIF
  ENDDO

  ! **  MODIFY EAST-WEST CELL MAPPING FOR PERIOD GRID IN E-W DIRECTION
  IF( ISCONNECT >= 2 )THEN
    DO NPN=1,NPEWBP
      L=LIJ(IWPEW(NPN),JWPEW(NPN))
      LWC(L)=LIJ(IEPEW(NPN),JEPEW(NPN))
      IF( IJCT(IEPEW(NPN),JEPEW(NPN)-1) == 9 )THEN  !LSWC(L)=LIJ(I-1,J-1)
        LSWC(L)=LC
      ELSE
        LSWC(L)=LIJ(IEPEW(NPN),JEPEW(NPN)-1)
      ENDIF
      IF( IJCT(IEPEW(NPN),JEPEW(NPN)+1) == 9 )THEN
        LNWC(L)=LC
      ELSE
        LNWC(L)=LIJ(IEPEW(NPN),JEPEW(NPN)+1)
      ENDIF
      
      L=LIJ(IEPEW(NPN),JEPEW(NPN))
      LEC(L)=LIJ(IWPEW(NPN),JWPEW(NPN))
      IF( IJCT(IWPEW(NPN),JWPEW(NPN)-1) == 9 )THEN  !LSEC(L)=LIJ(I+1,J-1)
        LSEC(L)=LC
      ELSE
        LSEC(L)=LIJ(IWPEW(NPN),JWPEW(NPN)-1)
      ENDIF
      IF( IJCT(IWPEW(NPN),JWPEW(NPN)+1) == 9 )THEN
        LNEC(L)=LC
      ELSE
        LNEC(L)=LIJ(IWPEW(NPN),JWPEW(NPN)+1)
      ENDIF
    ENDDO
  ENDIF

  ! **  MODIFY NORTH-SOUTH CELL MAPPING FOR PERIOD GRID IN N-S DIRECTION
  IF( ISCONNECT == 1 .OR. ISCONNECT == 3 )THEN
    DO NPN=1,NPNSBP
      LS=LIJ(ISPNS(NPN),JSPNS(NPN))
      LSC(LS)=LIJ(INPNS(NPN),JNPNS(NPN))
      IF( IJCT(INPNS(NPN)+1,JNPNS(NPN)) == 9 )THEN
        LSEC(LS)=LC
      ELSE
        LSEC(LS)=LIJ(INPNS(NPN)+1,JNPNS(NPN))
      ENDIF
      IF( IJCT(INPNS(NPN)-1,JNPNS(NPN)) == 9 )THEN
        LSWC(LS)=LC
      ELSE
        LSWC(LS)=LIJ(INPNS(NPN)-1,JNPNS(NPN))
      ENDIF
      LN=LIJ(INPNS(NPN),JNPNS(NPN))
      LNC(LN)=LIJ(ISPNS(NPN),JSPNS(NPN))
      IF( IJCT(ISPNS(NPN)+1,JSPNS(NPN)) == 9 )THEN
        LNEC(LN)=LC
      ELSE
        LNEC(LN)=LIJ(ISPNS(NPN)+1,JSPNS(NPN))
      ENDIF
      IF( IJCT(ISPNS(NPN)-1,JSPNS(NPN)) == 9 )THEN
        LNWC(LN)=LC
      ELSE
        LNWC(LN)=LIJ(ISPNS(NPN)-1,JSPNS(NPN))
      ENDIF
    ENDDO
  ENDIF

  ! **  SET LT NORTH AND SOUTH CELL IDENTIFIER ARRAYS
  LNCLT(1)=LCLT
  LSCLT(1)=LCLT
  LNCLT(LC)=1
  LSCLT(LC)=1
  LECLT(1)=LCLT
  LWCLT(1)=LCLT
  LECLT(LC)=1
  LWCLT(LC)=1

  DO L=2,LALT
    I=ILLT(L)
    J=JLLT(L)
    ! ** N & S
    IF( IJCTLT(I,J+1) == 9 )THEN
      LNCLT(L)=LCLT
    ELSE
      LNCLT(L)=LIJLT(I,J+1)
    ENDIF
    IF( IJCTLT(I,J-1) == 9 )THEN
      LSCLT(L)=LCLT
    ELSE
      LSCLT(L)=LIJLT(I,J-1)
    ENDIF
    
    ! ** W & E
    IF( IJCTLT(I+1,J) == 9 )THEN
      LECLT(L)=LCLT
    ELSE
      LECLT(L)=LIJLT(I+1,J)
    ENDIF
    IF( IJCTLT(I-1,J) == 9 )THEN
      LWCLT(L)=LCLT
    ELSE
      LWCLT(L)=LIJLT(I-1,J)
    ENDIF
    
  ENDDO

  ! **  MODIFY LT NORTH-SOUTH CELL MAPPING FOR PERIOD GRID IN N-S DIRECTION
  IF( ISCONNECT == 1.OR.ISCONNECT == 3 )THEN
    DO NPN=1,NPNSBP
      ! SET NORTH CELL SOUTH OF SOUTH CELL
      LS=LIJLT(ISPNS(NPN),JSPNS(NPN))
      LSCLT(LS)=LIJLT(INPNS(NPN),JNPNS(NPN))

      !     SET SOUTH CELL NORTH OF NORTH CELL
      LN=LIJLT(INPNS(NPN),JNPNS(NPN))
      LNCLT(LN)=LIJLT(ISPNS(NPN),JSPNS(NPN))
    END DO
  END IF
  
  ! **  MODIFY 6 CELLS FOR W-E CONNECTIONS (IJCTLT)
  IF( ISCONNECT >= 2 )THEN
    DO NPN=1,NPEWBP
      LE=LIJLT(IEPEW(NPN),JEPEW(NPN))
      LECLT(LE)=LIJLT(IWPEW(NPN),JWPEW(NPN))
      
      LW=LIJLT(IWPEW(NPN),JWPEW(NPN))
      LWCLT(LW)=LIJLT(IEPEW(NPN),JEPEW(NPN))
    END DO
  ENDIF

    101 FORMAT(' LR,LTMP = ',2I6/)
    102 FORMAT(' LR,LTMP = ',2I6/)
    103 FORMAT(' LN= 1, LR,LTMP,ITMP,JTMP = ',4I6/)
    104 FORMAT(' LN=LC, LR,LTMP,ITMP,JTMP = ',4I6/)
    105 FORMAT(' NERR, LR,LTMP,ITMP,JTMP,INTMP,JNTMP = ',6I6/)
    106 FORMAT(' NERR, LR,LTMP,ITMP,JTMP,INTMP,JNTMP = ',6I6/)
    107 FORMAT(' LS= 1, LR,LTMP,ITMP,JTMP = ',4I6/)
    108 FORMAT(' LS=LC, LR,LTMP,ITMP,JTMP = ',4I6/)
    109 FORMAT(' SERR, LR,LTMP,ITMP,JTMP,ISTMP,JSTMP = ',6I6/)
    110 FORMAT(' SERR, LR,LTMP,ITMP,JTMP,ISTMP,JSTMP = ',6I6/)
    111 FORMAT(' LE= 1, LR,LTMP,ITMP,JTMP = ',4I6/)
    112 FORMAT(' LE=LC, LR,LTMP,ITMP,JTMP = ',4I6/)
    113 FORMAT(' EERR, LR,LTMP,ITMP,JTMP,IETMP,JETMP = ',6I6/)
    114 FORMAT(' EERR, LR,LTMP,ITMP,JTMP,IETMP,JETMP = ',6I6/)
    115 FORMAT(' LW= 1, LR,LTMP,ITMP,JTMP = ',4I6/)
    116 FORMAT(' LW=LC, LR,LTMP,ITMP,JTMP = ',4I6/)
    117 FORMAT(' WERR, LR,LTMP,ITMP,JTMP,IWTMP,JWTMP = ',6I6/)
    118 FORMAT(' WERR, LR,LTMP,ITMP,JTMP,IWTMP,JWTMP = ',6I6/)
    201 FORMAT(' LB,LTMP = ',2I6/)
    202 FORMAT(' LB,LTMP = ',2I6/)
    203 FORMAT(' LN= 1, LB,LTMP,ITMP,JTMP = ',4I6/)
    204 FORMAT(' LN=LC, LB,LTMP,ITMP,JTMP = ',4I6/)
    205 FORMAT(' NERR, LB,LTMP,ITMP,JTMP,INTMP,JNTMP = ',6I6/)
    206 FORMAT(' NERR, LB,LTMP,ITMP,JTMP,INTMP,JNTMP = ',6I6/)
    207 FORMAT(' LS= 1, LB,LTMP,ITMP,JTMP = ',4I6/)
    208 FORMAT(' LS=LC, LB,LTMP,ITMP,JTMP = ',4I6/)
    209 FORMAT(' SERR, LB,LTMP,ITMP,JTMP,ISTMP,JSTMP = ',6I6/)
    210 FORMAT(' SERR, LB,LTMP,ITMP,JTMP,ISTMP,JSTMP = ',6I6/)
    211 FORMAT(' LE= 1, LB,LTMP,ITMP,JTMP = ',4I6/)
    212 FORMAT(' LE=LC, LB,LTMP,ITMP,JTMP = ',4I6/)
    213 FORMAT(' EERR, LB,LTMP,ITMP,JTMP,IETMP,JETMP = ',6I6/)
    214 FORMAT(' EERR, LB,LTMP,ITMP,JTMP,IETMP,JETMP = ',6I6/)
    215 FORMAT(' LW= 1, LB,LTMP,ITMP,JTMP = ',4I6/)
    216 FORMAT(' LW=LC, LB,LTMP,ITMP,JTMP = ',4I6/)
    217 FORMAT(' WERR, LB,LTMP,ITMP,JTMP,IWTMP,JWTMP = ',6I6/)
    218 FORMAT(' WERR, LB,LTMP,ITMP,JTMP,IWTMP,JWTMP = ',6I6/)
    119 FORMAT('       SUB(LETMP) = ',F10.2/)
    120 FORMAT('       SUB(LTMP)  = ',F10.2/)

  ! *** EFDC CELL MAP LOGGING
  WRITE(8,'(7A6)') 'I','J','L','LWC','LEC','LSC','LNC'
  DO L=2,LA  
    WRITE(8,'(7I6)') IL(L),JL(L),L,LWC(L),LEC(L),LSC(L),LNC(L)
  ENDDO
      
  ! **  DEFINE MAPPING TO 3D GRAPHICS GRID
  IF( ISCLO == 0 .OR. NWGG == 0 )THEN
    IG=IC
    JG=JC
  ELSE
    OPEN(1,FILE='gcellmp.inp',STATUS='UNKNOWN')

    STR = READSTR(1) 
   
    READ(1,*)IG,JG
    DO NW=1,NWGG
      READ(1,*)IGTMP,JGTMP,ICOMP,JCOMP
      LTMP=LIJ(ICOMP,JCOMP)
      IWGG(NW)=IGTMP
      JWGG(NW)=JGTMP
      LWGG(NW)=LTMP
    ENDDO
    CLOSE(1)
  ENDIF

  RETURN
END

