FUNCTION CSNDSET(SND,SDEN,IOPT)
  !
  ! CHANGE RECORD
  ! **  CALCULATES HINDERED SETTLING CORRECTION FOR CLASS NS NONCOHESIVE
  ! **  SEDIMENT

  IMPLICIT NONE
  
  INTEGER :: IOPT
  REAL :: CSNDSET,SND,SDEN,ROPT

  ROPT=FLOAT(IOPT)
  CSNDSET=(1.-SDEN*SND)**ROPT

END FUNCTION

