FUNCTION FSBDLD(DIASED,GPDIASED,D50,DEP,PEXP,PHID,CSHIELDS,SBDLDP,ISOPT)

  ! CHANGE RECORD
  !  MODIFED TO INCLUDE ALTERNATE FORMULAS FOR BED LOAD PHI
  !
  !
  ! **  CALCULATES DIMENSIONLESS BED LOAD TRANSPORT COEFFICIENT
  ! **  ISOPT=0  USE CONSTANT VALUE
  !

  IMPLICIT NONE

  INTEGER :: ISOPT
  REAL :: FSBDLD,DIASED,GPDIASED,D50,DEP,PEXP,PHID,CSHIELDS,SBDLDP,RD,TMP,TMP1,TMP2

  IF( ISOPT == 0 ) FSBDLD=SBDLDP
  
  ! **  ISOPT=1  BASED ON
  ! **
  ! **  VAN RIJN, L. C., 1984: SEDIMENT TRANSPORT, PART I: BED
  ! **  LOAD TRANSPORT, J. HYDRAULIC ENGINEERING, 110, 1431-1455.
  IF( ISOPT == 1 )THEN
    RD=DIASED*SQRT(GPDIASED)*1.E6
    RD=(1./RD)**0.2
    TMP=CSHIELDS**2.1
    FSBDLD=0.053*RD/TMP
  ENDIF

  ! **  ISOPT=2  BASED ON MODIFIED ENGULAND-HANSEN FORMULA
  ! **  REFERENCE TO BE ADDED
  IF( ISOPT == 2 )THEN
    TMP1=(DEP/D50)**0.33333
    TMP2=(PEXP/PHID)**1.125
    FSBDLD=2.0367*TMP1*TMP2
  ENDIF

  ! **  ISOPT=3  BASED ON WU, WANG AND JIA, J. HYDR. RES. V38, 2000
  IF( ISOPT == 3 )THEN
    TMP1=0.03*((PHID/PEXP)**0.6)
    TMP2=TMP1**2.2
    FSBDLD=0.0053/TMP2
  ENDIF

END FUNCTION

