
SUBROUTINE JPACON(ITVAL,ZVAL,UAG,VAG,WAG)

  ! *** JET/PLUME SUB-MODEL SUBROUTINE
  ! *** RETURNS THE AMBIENT CONDITIONS FOR VARIABLE WQ CONDITIONS BASED 

  ! CHANGE RECORD
  
  USE GLOBAL
  IMPLICIT NONE   
                                                                                                       
  INTEGER :: ITVAL,NT,NS,NX,NZ,NZP                                                                             
  REAL    :: WTNZP,WTNZ,ZVAL                                                                                                
  REAL    :: UAG,VAG,WAG,DZK

  IF( ZVAL < ZAD(1,ITVAL) )THEN
    UAG=UAGD(1,ITVAL)
    VAG=VAGD(1,ITVAL)
    WAG=WAGD(1,ITVAL)
    SALA=SALAD(1,ITVAL)
    TEMA=TEMAD(1,ITVAL)
    DYEA=DYEAD(1,ITVAL)
    SFLA=SFLAD(1,ITVAL)
    DO NT=1,NTOX
      TOXA(NT)=TOXAD(1,NT,ITVAL)
    ENDDO
    DO NS=1,NSED
      SEDA(NS)=SEDAD(1,NS,ITVAL)
    ENDDO
    DO NX=1,NSND
      SNDA(NX)=SNDAD(1,NX,ITVAL)
    ENDDO
    RETURN
  ENDIF

  ! *** GET CONCENTRATIONS BASED ON PLUME ELEVATION (ZVAL) (NAZD = KC)
  IF( ZVAL >= ZAD(NAZD,ITVAL) )THEN
    ! JET/PLUME ELEVATION IS ABOVE THE TOP LAYER MIDPOINT
    UAG=UAGD(NAZD,ITVAL)
    VAG=VAGD(NAZD,ITVAL)
    WAG=WAGD(NAZD,ITVAL)
    SALA=SALAD(NAZD,ITVAL)
    TEMA=TEMAD(NAZD,ITVAL)
    DYEA=DYEAD(NAZD,ITVAL)
    SFLA=SFLAD(NAZD,ITVAL)
    DO NT=1,NTOX
      TOXA(NT)=TOXAD(NAZD,NT,ITVAL)
    ENDDO
    DO NS=1,NSED
      SEDA(NS)=SEDAD(NAZD,NS,ITVAL)
    ENDDO
    DO NX=1,NSND
      SNDA(NX)=SNDAD(NAZD,NX,ITVAL)
    ENDDO
    RETURN
  ENDIF

  ! *** DETERMINE WHICH LAYER TO EXTRACT THE AMBIENT CONDITIONS FROM
  NZ=1
  ! *** LOOP OVER LAYERS
   1000 CONTINUE

  ! *** NZP = LAYER ABOVE
  NZP=NZ+1
  IF( ZVAL >= ZAD(NZ,ITVAL) .AND. ZVAL < ZAD(NZP,ITVAL) )THEN
    ! *** INTERPOLATE AMBIENT CONDITIONS FROM LAYER INTERVAL
    DZK =1./(ZAD(NZP,ITVAL)-ZAD(NZ,ITVAL))
    WTNZ=DZK*(ZAD(NZP,ITVAL)-ZVAL)
    WTNZP=DZK*(ZVAL-ZAD(NZ,ITVAL))
    UAG=WTNZ*UAGD(NZ,ITVAL)+WTNZP*UAGD(NZP,ITVAL)
    VAG=WTNZ*VAGD(NZ,ITVAL)+WTNZP*VAGD(NZP,ITVAL)
    WAG=WTNZ*WAGD(NZ,ITVAL)+WTNZP*WAGD(NZP,ITVAL)
    SALA=WTNZ*SALAD(NZ,ITVAL)+WTNZP*SALAD(NZP,ITVAL)
    TEMA=WTNZ*TEMAD(NZ,ITVAL)+WTNZP*TEMAD(NZP,ITVAL)
    DYEA=WTNZ*DYEAD(NZ,ITVAL)+WTNZP*DYEAD(NZP,ITVAL)
    SFLA=WTNZ*SFLAD(NZ,ITVAL)+WTNZP*SFLAD(NZP,ITVAL)
    DO NT=1,NTOX
      TOXA(NT)=WTNZ*TOXAD(NZ,NT,ITVAL)+WTNZP*TOXAD(NZP,NT,ITVAL)
    ENDDO
    DO NS=1,NSED
      SEDA(NS)=WTNZ*SEDAD(NZ,NS,ITVAL)+WTNZP*SEDAD(NZP,NS,ITVAL)
    ENDDO
    DO NX=1,NSND
      SNDA(NX)=WTNZ*SNDAD(NZ,NX,ITVAL)+WTNZP*SNDAD(NZP,NX,ITVAL)
    ENDDO
    ! *** DSI NOTE - MISSING WATER QUALITY
    RETURN
  ELSE
    NZ=NZ+1
    GOTO 1000
  ENDIF
  RETURN
END

