SUBROUTINE RCAHQ

  ! **  SUBROUTINE FOR INTERFACING RCA MODEL
  ! **  MODIFIED FROM WCA2A PROUDCTION VERSION
  ! **  WITH WITHDRAWL-RETURN FLOW OPTION DEACTIVATED BY CNWR

  ! CHANGE RECORD

  ! *** PMC  THIS ROUTINE USES HMP, THE STATIC IC DEPTH.  SHOULDN'T IT USE HP?
  USE GLOBAL
  
  IMPLICIT NONE
  
  INTEGER :: NSKIP,ISDRCA,IDMPCL,JDMPCL,NS,NCTL,NWR,NMD,L,I,J,K,KK,NMID,NQSTMP,LN,LU,LD

  REAL    :: TIMTMP,SQRTMP,TIME,TIMMID,TAVGTMP,TMPVAL
  REAL,ALLOCATABLE,DIMENSION(:) :: DZRCA
  REAL,ALLOCATABLE,DIMENSION(:) :: DZZRCA
  REAL,ALLOCATABLE,DIMENSION(:) :: QINRCA
  REAL,ALLOCATABLE,DIMENSION(:,:) :: QINTFL
  REAL,ALLOCATABLE,DIMENSION(:,:) :: TMPARA

  ALLOCATE(DZRCA(KCM+1))
  ALLOCATE(DZZRCA(KCM+1))
  ALLOCATE(QINRCA(NQSIJM))
  ALLOCATE(QINTFL(NQINFLM,KCM))
  ALLOCATE(TMPARA(ICM,JCM))
  DZRCA=0.
  DZZRCA=0.
  QINRCA=0.
  QINTFL=0.
  TMPARA=0.
  !
  ! **  WRITE TIME INVARIANT FILES ON FIRST ENTRY
  !
  IF( JSWASP == 0 ) GOTO 1000
  JSWASP=0
  OPEN(1,FILE=OUTDIR//'EFDC.RCA',STATUS='UNKNOWN')
  !
  ! **  READ I,J LOCATION OF THE DUMP CELL (AN ACTIVE WATER CELL)
  !
  DO NSKIP=1,4
    READ(1,100)
  ENDDO
  READ(1,*)ISDRCA,IDMPCL,JDMPCL
  CLOSE(1)
  !
  ! **  WRITE I,J INDICES DEFINING FLOWS BETWEEN ARBITARY CELLS
  ! **  (POSTIVE FLOW DIRECTION DEFINED FROM FIRST TO SECOND I,J PAIR)
  !
  OPEN(1,FILE=OUTDIR//'flwmap.inp',STATUS='UNKNOWN')
  CLOSE(1,STATUS='DELETE')
  OPEN(1,FILE=OUTDIR//'flwmap.inp',STATUS='UNKNOWN')
  NINTFL=0
  IF( NQSIJ > 0 )THEN
    DO NS=1,NQSIJ
      NINTFL=NINTFL+1
      WRITE(1,101)IDMPCL,JDMPCL,IQS(NS),JQS(NS)
    ENDDO
  ENDIF
  IF( NQCTL > 0 )THEN
    DO NCTL=1,NQCTL
      NINTFL=NINTFL+1
      IF( IQCTLD(NCTL) > 0 )THEN
        WRITE(1,101) IQCTLU(NCTL),JQCTLU(NCTL), &
            IQCTLD(NCTL),JQCTLD(NCTL)
      ELSE
        WRITE(1,101)IQCTLU(NCTL),JQCTLU(NCTL), &
            IDMPCL,JDMPCL
      ENDIF
    ENDDO
  ENDIF
  IF( NQWR > 0 )THEN
    DO NWR=1,NQWR
      NINTFL=NINTFL+1
      WRITE(1,101)IQWRU(NWR),JQWRU(NWR),IQWRD(NWR),JQWRD(NWR)
    ENDDO
  ENDIF
  IF( MDCHH > 0 )THEN
    DO NMD=1,MDCHH
      IF( IMDCHU(NMD) > 1 )THEN
        NINTFL=NINTFL+1
        WRITE(1,101)IMDCHU(NMD),JMDCHU(NMD),IMDCHH(NMD),JMDCHH(NMD)
      ENDIF
    ENDDO
    DO NMD=1,MDCHH
      IF( IMDCHV(NMD) > 1 )THEN
        NINTFL=NINTFL+1
        WRITE(1,101)IMDCHV(NMD),JMDCHV(NMD),IMDCHH(NMD),JMDCHH(NMD)
      ENDIF
    ENDDO
  ENDIF
  CLOSE(1)
  OPEN(1,FILE=OUTDIR//'EFDCRCA.LOG',STATUS='UNKNOWN')
  CLOSE(1,STATUS='DELETE')
  OPEN(1,FILE=OUTDIR//'EFDCRCA.LOG',STATUS='UNKNOWN')
  ICRCA1=IDMPCL
  ICRCA2=JDMPCL
  ICRCA3=ISDRCA
  NCRCA1=NINTFL
  WRITE(1,102)IC,JC,KC
  WRITE(1,103)NINTFL
  WRITE(1,104)IDMPCL,JDMPCL
  TIMTMP=TCON*TBEGIN/86400.
  WRITE(1,105)TIMTMP
  CLOSE(1)
  OPEN(1,FILE=OUTDIR//'INFLWIJ.DAT',STATUS='UNKNOWN')
  CLOSE(1,STATUS='DELETE')
  OPEN(1,FILE=OUTDIR//'INFLWIJ.DAT',STATUS='UNKNOWN')
  WRITE(1,110)
  WRITE(1,111)
  IF( NQSIJ >= 1 )THEN
    DO NS=1,NQSIJ
      WRITE(1,112)NS,IQS(NS),JQS(NS)
    ENDDO
  ENDIF
  CLOSE(1)
  !
  ! **  WRITE GRID GEOMETRY, INCLUDING INITIAL DEPTH
  !
  OPEN(1,FILE=OUTDIR//'GCM_GEOM',FORM='UNFORMATTED' &
        ,STATUS='UNKNOWN')
  CLOSE(1,STATUS='DELETE')
  OPEN(1,FILE=OUTDIR//'GCM_GEOM',FORM='UNFORMATTED' &
        ,STATUS='UNKNOWN')
  DO L=1,LC
    HTMP(L)=HP(L)
  ENDDO
  DZRCA(KC+1)=0.
  DZZRCA(KC+1)=0.
  DZZRCA(1)=0.
  DO K=1,KC
    KK=KC+1-K
    DZRCA(KK)=DZC(L,K)
  ENDDO
  IF( KC > 1 )THEN
    DO K=1,KS
      KK=KS+2-K
      DZZRCA(KK)=DZG(L,K)
    ENDDO
  ENDIF
  WRITE(1)DZRCA,DZZRCA
  SQRTMP=SQRT(0.5)
  DO J=1,JC
    DO I=1,IC
      TMPARA(I,J)=1.E-6
    ENDDO
  ENDDO
  DO J=1,JC
    DO I=1,IC
      IF( IJCT(I,J) >= 1 .AND. IJCT(I,J) <= 5 )THEN
        TMPARA(I,J)=HP(LIJ(I,J))
      ENDIF
    ENDDO
  ENDDO
  WRITE(1)TMPARA
  DO J=1,JC
    DO I=1,IC
      TMPARA(I,J)=DX
    ENDDO
  ENDDO
  DO J=1,JC
    DO I=1,IC
      IF( IJCT(I,J) >= 1 .AND. IJCT(I,J) <= 4 )THEN
        TMPARA(I,J)=SQRTMP*DXP(LIJ(I,J))
      ENDIF
      IF( IJCT(I,J) == 5 )THEN
        TMPARA(I,J)=DXP(LIJ(I,J))
      ENDIF
    ENDDO
  ENDDO
  WRITE(1)TMPARA
  DO J=1,JC
    DO I=1,IC
      TMPARA(I,J)=DY
    ENDDO
  ENDDO
  DO J=1,JC
    DO I=1,IC
      IF( IJCT(I,J) >= 1 .AND. IJCT(I,J) <= 4 )THEN
        TMPARA(I,J)=SQRTMP*DYP(LIJ(I,J))
      ENDIF
      IF( IJCT(I,J) == 5 )THEN
        TMPARA(I,J)=DYP(LIJ(I,J))
      ENDIF
    ENDDO
  ENDDO
  WRITE(1)TMPARA
  DO J=1,JC
    DO I=1,IC
      TMPARA(I,J)=0.
    ENDDO
  ENDDO
  DO J=1,JC
    DO I=1,IC
      IF( IJCT(I,J) >= 1 .AND. IJCT(I,J) <= 5 )THEN
        TMPARA(I,J)=1.
      ENDIF
    ENDDO
  ENDDO
  WRITE(1)TMPARA
  CLOSE(1)
  OPEN(1,FILE=OUTDIR//'efdchyd.inp',FORM='UNFORMATTED' &
        ,STATUS='UNKNOWN')
  CLOSE(1,STATUS='DELETE')
  IF( ICRCA3 == 1 )THEN
    OPEN(1,FILE=OUTDIR//'EFDCHYD.ASC',STATUS='UNKNOWN')
    CLOSE(1,STATUS='DELETE')
  ENDIF
  OPEN(1,FILE=OUTDIR//'INFLOW.DAT',STATUS='UNKNOWN')
  CLOSE(1,STATUS='DELETE')
  OPEN(1,FILE=OUTDIR//'hydrlgy.inp',FORM='UNFORMATTED' &
        ,STATUS='UNKNOWN')
  CLOSE(1,STATUS='DELETE')
  IF( ICRCA3 == 1 )THEN
    OPEN(1,FILE=OUTDIR//'HYDRLGY.ASC',STATUS='UNKNOWN')
    CLOSE(1,STATUS='DELETE')
  ENDIF
  OPEN(1,FILE=OUTDIR//'intflw.inp',FORM='UNFORMATTED' &
        ,STATUS='UNKNOWN')
  CLOSE(1,STATUS='DELETE')
  IF( ICRCA3 == 1 )THEN
    OPEN(1,FILE=OUTDIR//'INTFLW.ASC',STATUS='UNKNOWN')
    CLOSE(1,STATUS='DELETE')
  ENDIF
    100 FORMAT(120X)
    101 FORMAT(4I10)
    102 FORMAT(' NROW,NCOL,NLAYR = ',3I10/)
    103 FORMAT(' NO INTERNAL FLOWS, NINTFL (LINES) IN FLWMAP.INP = ', &
      I10/)
    104 FORMAT(' ROW, COLUMN INDICES OF DUMP CELL = ',2I10/)
    105 FORMAT(' SIMULATION STARTING TIME IN DAYS = ',F12.6/)
    106 FORMAT(' TIME IN DAYS AT MIDDLE OF AVERAGING PERIOD = ',F12.6/)
    110 FORMAT(' LOCATION OF INFLOWS ',/)
    111 FORMAT(' INFLOW #   ROW INDEX   COLUMN INDEX ',/)
    112 FORMAT(2X,I5,7X,I5,7X,I5)
    120 FORMAT(F12.6,13F12.4)
   1000 CONTINUE
  IF( ISDYNSTP == 0 )THEN
    TIME=(DT*FLOAT(N)+TCON*TBEGIN)/86400.
  ELSE
    TIME=TIMESEC/86400.
  ENDIF
  NMID=N-(NTSMMT/2)
  TIMMID=(DT*FLOAT(NMID)+TCON*TBEGIN)/86400.
  !
  ! **  WRITE TIME AT END OF AVERAGING PERIOD TO EFDCRCA.LOG
  !
  OPEN(1,FILE=OUTDIR//'EFDCRCA.LOG',STATUS='UNKNOWN' &
        ,POSITION='APPEND')
  WRITE(1,106)TIMMID
  CLOSE(1)
  !
  ! **  WRITE INFLOWS AT END OF AVERAGING PERIOD TO INFLOW.DAT
  !
  OPEN(1,FILE=OUTDIR//'INFLOW.DAT',STATUS='UNKNOWN' &
        ,POSITION='APPEND')
  DO NS=1,NQSIJ
    QINRCA(NS)=0.
  ENDDO
  DO NS=1,NQSIJ
    NQSTMP=NQSERQ(NS)
    IF( NQSTMP > 0 )THEN
      DO K=1,KC
        QINRCA(NS)=QINRCA(NS)+QSRTLPP(K,NQSTMP)+MAX(QSS(K,NS),0.)
      ENDDO
    ELSE
      DO K=1,KC
        QINRCA(NS)=QINRCA(NS)+MAX(QSS(K,NS),0.)
      ENDDO
    ENDIF
  ENDDO
  WRITE(1,120)TIME,(QINRCA(NS),NS=1,NQSIJ)
  CLOSE(1)
  !
  ! **  WRITE INTERNAL FLOWS TO INTFLW.INP
  !
  OPEN(1,FILE=OUTDIR//'intflw.inp',FORM='UNFORMATTED' &
        ,STATUS='UNKNOWN', POSITION='APPEND')
  IF( ICRCA3 == 1 )THEN
    OPEN(2,FILE=OUTDIR//'INTFLW.ASC',STATUS='UNKNOWN' &
          ,POSITION='APPEND')
    WRITE(2,106)TIME
  ENDIF
  DO K=1,KC
    DO NS=1,NCRCA1
      QINTFL(NS,K)=0.
    ENDDO
  ENDDO
  NINTFL=0
  IF( NQSIJ > 0 )THEN
    DO NS=1,NQSIJ
      NINTFL=NINTFL+1
      NQSTMP=NQSERQ(NS)
      IF( NQSTMP > 0 )THEN
        DO K=1,KC
          QINTFL(NINTFL,K)=QINTFL(NINTFL,K)+QSRTLPN(K,NQSTMP) &
              +MIN(QSS(K,NS),0.)
        ENDDO
      ELSE
        DO K=1,KC
          QINTFL(NINTFL,K)=QINTFL(NINTFL,K)+MIN(QSS(K,NS),0.)
        ENDDO
      ENDIF
    ENDDO
  ENDIF
  IF( NQCTL > 0 )THEN
    DO NCTL=1,NQCTL
      NINTFL=NINTFL+1
      DO K=1,KC
        QINTFL(NINTFL,K)=QINTFL(NINTFL,K)+QCTLTLP(K,NCTL)
      ENDDO
    ENDDO
  ENDIF
  IF( NQWR > 0 )THEN
    DO NWR=1,NQWR
      NQSTMP=NQWRSERQ(NWR)
      NINTFL=NINTFL+1
      DO K=1,KC
        IF( K == KQWRU(NWR) )THEN
          QINTFL(NINTFL,K)=QINTFL(NINTFL,K)+QWRSERTLP(NQSTMP) &
              +QWR(NWR)
        ENDIF
      ENDDO
    ENDDO
  ENDIF
  IF( MDCHH > 0 )THEN
    DO NMD=1,MDCHH
      IF( IMDCHU(NMD) > 1 )THEN
        NINTFL=NINTFL+1
        DO K=1,KC
          QINTFL(NINTFL,K)=QINTFL(NINTFL,K)+QCHNULP(NMD)*DZC(L,K)
        ENDDO
      ENDIF
    ENDDO
    DO NMD=1,MDCHH
      IF( IMDCHV(NMD) > 1 )THEN
        NINTFL=NINTFL+1
        DO K=1,KC
          QINTFL(NINTFL,K)=QINTFL(NINTFL,K)+QCHNULP(NMD)*DZC(L,K)
        ENDDO
      ENDIF
    ENDDO
  ENDIF
  WRITE(1)QINTFL
  IF( ICRCA3 == 1 )THEN
    WRITE(2,213)
    DO NS=1,NINTFL
      WRITE(2,211)NS,(QINTFL(NS,K),K=1,KC)
    ENDDO
  ENDIF
  CLOSE(1)
  IF( ICRCA3 == 1 ) CLOSE(2)
  !
  ! **  WRITE TRANSPORTS TO EFDCHDY.INP
  !
  OPEN(1,FILE=OUTDIR//'efdchyd.inp',FORM='UNFORMATTED' &
        ,STATUS='UNKNOWN', POSITION='APPEND')
  WRITE(1)TIMMID
  IF( ICRCA3 == 1 )THEN
    OPEN(2,FILE=OUTDIR//'EFDCHYD.ASC',STATUS='UNKNOWN' &
          ,POSITION='APPEND')
    WRITE(2,106) TIMMID
  ENDIF
  TAVGTMP=FLOAT(NTSMMT)*DT
  !
  ! **  WRITE QX
  !
  DO J=1,JC
    DO I=1,IC
      TMPARA(I,J)=0.
    ENDDO
  ENDDO
  DO KK=1,KC
    K=KC+1-KK
    DO L=2,LA
      TMPVAL=DZC(L,K)*DYU(L)*UHLPF(L,K)
      TMPARA(IL(L),JL(L))=TMPVAL
      TVAR1E(L,K)=TMPVAL
    ENDDO
    WRITE(1)TMPARA
  ENDDO
  IF( ICRCA3 == 1 )THEN
    WRITE(2,201)
    DO L=2,LA
      WRITE(2,200)L,IL(L),JL(L),(TVAR1E(L,K),K=1,KC)
    ENDDO
    WRITE(2,210)
  ENDIF
  !
  ! **  WRITE QY
  !
  DO J=1,JC
    DO I=1,IC
      TMPARA(I,J)=0.
    ENDDO
  ENDDO
  DO KK=1,KC
    K=KC+1-KK
    DO L=2,LA
      TMPVAL=DZC(L,K)*DXV(L)*VHLPF(L,K)
      TMPARA(IL(L),JL(L))=TMPVAL
      TVAR1E(L,K)=TMPVAL
    ENDDO
    WRITE(1)TMPARA
  ENDDO
  IF( ICRCA3 == 1 )THEN
    WRITE(2,202)
    DO L=2,LA
      WRITE(2,200)L,IL(L),JL(L),(TVAR1E(L,K),K=1,KC)
    ENDDO
    WRITE(2,210)
  ENDIF
  !
  ! **  LOAD NET DEPTH INTEGRATED INFLOWS INTO TVAR3E AND
  ! **  OUT FLOWS INTO TVAR3N
  !
  DO L=2,LA
    LN=LNC(L)
    TVAR3E(L)=0.
    TVAR3N(L)=0.
    DO K=1,KC
      TVAR3E(L)=TVAR3E(L)+DZC(L,K)*( DYU(L)*UHLPF(L,K) &
          +DXV(L)*VHLPF(L,K) )
      TVAR3N(L)=TVAR3N(L)+DZC(L,K)*( DYU(LEC(L))*UHLPF(LEC(L),K) &
          +DXV(LN )*VHLPF(LN ,K) )
    ENDDO
  ENDDO
  IF( MDCHH >= 1 )THEN
    DO NMD=1,MDCHH
      IF( MDCHTYP(NMD) == 1 )THEN
        TVAR3E(LMDCHH(NMD))=TVAR3E(LMDCHH(NMD)) &
            +QCHNULP(NMD)
        TVAR3N(LMDCHU(NMD))=TVAR3N(LMDCHU(NMD)) &
            +QCHNULP(NMD)
      ENDIF
      IF( MDCHTYP(NMD) == 2 )THEN
        TVAR3E(LMDCHH(NMD))=TVAR3E(LMDCHH(NMD)) &
            +QCHNVLP(NMD)
        TVAR3N(LMDCHV(NMD))=TVAR3N(LMDCHV(NMD)) &
            +QCHNVLP(NMD)
      ENDIF
      IF( MDCHTYP(NMD) == 3 )THEN
        TVAR3E(LMDCHH(NMD))=TVAR3E(LMDCHH(NMD)) &
            +QCHNULP(NMD)+QCHNVLP(NMD)
        TVAR3N(LMDCHU(NMD))=TVAR3N(LMDCHU(NMD)) &
            +QCHNULP(NMD)+QCHNVLP(NMD)
      ENDIF
    ENDDO
  ENDIF
  !
  ! **  WRITE QZ
  !
  DO J=1,JC
    DO I=1,IC
      TMPARA(I,J)=0.
    ENDDO
  ENDDO
  IF( KC > 1 )THEN
    DO K=1,KS
      DO L=2,LA
        LN=LNC(L)
        WLPF(L,K)=SWB(L)*( WLPF(L,K-1) &
            +DZC(L,K)*(DYU(L)*UHLPF(L,K)+DXV(L)*VHLPF(L,K))*DXYIP(L) &
            -TVAR3E(L)*DXYIP(L) &
            -DZC(L,K)*(DYU(LEC(L))*UHLPF(LEC(L),K) &
            +DXV(LN )*VHLPF(LN ,K))*DXYIP(L) &
            +TVAR3N(L)*DXYIP(L) ) &
            +SWB(L)*( QSUMLPF(L,K)-DZC(L,K)*QSUMELPF(L) )*DXYIP(L)
      ENDDO
    ENDDO
  ENDIF
  IF( KC > 1 )THEN
    DO KK=0,KC
      K=KC+1-KK
      DO L=2,LA
        TMPARA(IL(L),JL(L))=DXYP(L)*WLPF(L,K)
      ENDDO
      WRITE(1)TMPARA
      IF( ICRCA3 == 1 .AND. K >= 1 )THEN
        DO L=2,LA
          TVAR1E(L,K)=DXYP(L)*WLPF(L,K)
        ENDDO
      ENDIF
    ENDDO
  ENDIF
  IF( ICRCA3 == 1 .AND. KC > 1 )THEN
    WRITE(2,203)
    DO L=2,LA
      WRITE(2,200)L,IL(L),JL(L),(TVAR1E(L,K),K=1,KS)
    ENDDO
    WRITE(2,210)
  ENDIF
  !
  ! **  WRITE AHX
  !
  DO J=1,JC
    DO I=1,IC
      TMPARA(I,J)=0.
    ENDDO
  ENDDO
  !
  ! **  WRITE AHY
  !
  DO J=1,JC
    DO I=1,IC
      TMPARA(I,J)=0.
    ENDDO
  ENDDO
  !
  ! **  WRITE AZ
  !
  DO J=1,JC
    DO I=1,IC
      TMPARA(I,J)=0.
    ENDDO
  ENDDO
  IF( KC > 1 )THEN
    DO KK=0,KC
      K=KC+1-KK
      IF( K >= 1 .AND. K <= KS )THEN
        DO L=2,LA
          TMPARA(IL(L),JL(L))=HP(L)*AB(L,K)
        ENDDO
      ELSE
        DO L=2,LA
          TMPARA(IL(L),JL(L))=0.
        ENDDO
      ENDIF
      WRITE(1)TMPARA
      IF( ICRCA3 == 1 .AND. K >= 1 )THEN
        DO L=2,LA
          TVAR1S(L,K)=HP(L)*AB(L,K)
        ENDDO
      ENDIF
    ENDDO
  ENDIF
  IF( ICRCA3 == 1 .AND. KC > 1 )THEN
    WRITE(2,206)
    DO L=2,LA
      WRITE(2,200)L,IL(L),JL(L),(TVAR1S(L,K),K=1,KS)
    ENDDO
    WRITE(2,210)
  ENDIF
  !
  ! **  WRITE WATER SURF ELV AT START OF AVG INTERVAL
  !
  DO J=1,JC
    DO I=1,IC
      TMPARA(I,J)=0.
    ENDDO
  ENDDO
  DO L=2,LA
    TMPARA(IL(L),JL(L))=HTMP(L)-HP(L)
    TVAR3W(L)=HTMP(L)-HP(L)
  ENDDO
  WRITE(1)TMPARA
  IF( ICRCA3 == 1 )THEN
    WRITE(2,215)
    DO L=2,LA
      WRITE(2,200)L,IL(L),JL(L),TVAR3W(L)
    ENDDO
    WRITE(2,210)
  ENDIF
  !
  ! **  CALCULATE TOTAL DEPTH AT END OF AVG INTERVAL
  ! **  HTMP IS NEW DEPTH, TMPARA IS DETA
  !
  DO J=1,JC
    DO I=1,IC
      TMPARA(I,J)=0.
    ENDDO
  ENDDO
  !
  ! **  UPDATE FOR TRANSPORTS, INTERNAL CHANNEL EXCHANGES AND
  ! **  HYDROLOGY
  !
  DO L=2,LA
    TMPARA(IL(L),JL(L))=TAVGTMP*SPB(L)*DXYIP(L)*( TVAR3E(L) &
        -TVAR3N(L)+RAINLPF(L)-EVPSLPF(L)-RINFLPF(L) )
  ENDDO
  !
  ! **  UPDATE FOR EXTERNAL INFLOWS
  !
  DO NS=1,NQSIJ
    L=LIJ(IQS(NS),JQS(NS))
    TMPARA(IQS(NS),JQS(NS))=TMPARA(IQS(NS),JQS(NS)) &
        +TAVGTMP*SPB(L)*DXYIP(L)*QINRCA(NS)
  ENDDO
  !
  ! **  UPDATE FOR NON CHANNEL EXCHANGE INTERNAL FLOWS
  !
  NINTFL=0
  IF( NQSIJ > 0 )THEN
    DO NS=1,NQSIJ
      L=LIJ(IQS(NS),JQS(NS))
      NINTFL=NINTFL+1
      DO K=1,KC
        TMPARA(IQS(NS),JQS(NS))= &
            TMPARA(IQS(NS),JQS(NS)) &
            -TAVGTMP*SPB(L)*DXYIP(L)*QINTFL(NINTFL,K)
      ENDDO
    ENDDO
  ENDIF
  IF( NQCTL > 0 )THEN
    DO NCTL=1,NQCTL
      LU=LIJ(IQCTLU(NCTL),JQCTLU(NCTL))
      LD=LIJ(IQCTLD(NCTL),JQCTLD(NCTL))
      NINTFL=NINTFL+1
      DO K=1,KC
        TMPARA(IQCTLU(NCTL),JQCTLU(NCTL))= &
            TMPARA(IQCTLU(NCTL),JQCTLU(NCTL)) &
            -TAVGTMP*SPB(LU)*DXYIP(LU)*QINTFL(NINTFL,K)
        TMPARA(IQCTLD(NCTL),JQCTLD(NCTL))= &
            TMPARA(IQCTLD(NCTL),JQCTLD(NCTL)) &
            +TAVGTMP*SPB(LD)*DXYIP(LD)*QINTFL(NINTFL,K)
      ENDDO
    ENDDO
  ENDIF
  IF( NQWR > 0 )THEN
    DO NWR=1,NQWR
      LU=LIJ(IQWRU(NWR),JQWRU(NWR))
      LD=LIJ(IQWRD(NWR),JQWRD(NWR))
      NINTFL=NINTFL+1
      DO K=1,KC
        IF( K == KQWRU(NWR) )THEN
          TMPARA(IQWRU(NWR),JQWRU(NWR))= &
              TMPARA(IQWRU(NWR),JQWRU(NWR)) &
              -TAVGTMP*SPB(LU)*DXYIP(LU)*QINTFL(NINTFL,KQWRU(NWR))
          TMPARA(IQWRD(NWR),JQWRD(NWR))= &
              TMPARA(IQWRD(NWR),JQWRD(NWR)) &
              +TAVGTMP*SPB(LD)*DXYIP(LD)*QINTFL(NINTFL,KQWRD(NWR))
        ENDIF
      ENDDO
    ENDDO
  ENDIF
  !
  ! **  COMPLETE UPDATE
  !
  DO L=2,LA
    HTMP(L)=(1.-SPB(L))*HP(L)+SPB(L)*( HTMP(L) &
        +TMPARA(IL(L),JL(L)) )
    TVAR3S(L)=HTMP(L)-HP(L)
  ENDDO
  WRITE(1)TMPARA
  IF( ICRCA3 == 1 )THEN
    WRITE(2,216)
    DO L=2,LA
      WRITE(2,200)L,IL(L),JL(L),TMPARA(IL(L),JL(L))
    ENDDO
    WRITE(2,210)
  ENDIF
  IF( ICRCA3 == 1 )THEN
    WRITE(2,207)
    DO L=2,LA
      WRITE(2,200)L,IL(L),JL(L),TVAR3W(L),HTMP(L), &
          TMPARA(IL(L),JL(L)),TVAR3S(L)
    ENDDO
    WRITE(2,210)
  ENDIF
  !
  ! **  WRITE SALINITY
  !
  DO J=1,JC
    DO I=1,IC
      TMPARA(I,J)=0.
    ENDDO
  ENDDO
  DO KK=1,KC
    K=KC+1-KK
    DO L=2,LA
      TMPARA(IL(L),JL(L))=SALLPF(L,K)
    ENDDO
    WRITE(1)TMPARA
  ENDDO
  IF( ICRCA3 == 1 )THEN
    WRITE(2,208)
    DO L=2,LA
      WRITE(2,200)L,IL(L),JL(L),(SALLPF(L,K),K=1,KC)
    ENDDO
    WRITE(2,210)
  ENDIF
  !
  ! **  WRITE TEMPERATURE
  !
  DO J=1,JC
    DO I=1,IC
      TMPARA(I,J)=0.
    ENDDO
  ENDDO
  DO KK=1,KC
    K=KC+1-KK
    DO L=2,LA
      TMPARA(IL(L),JL(L))=TEMLPF(L,K)
    ENDDO
    WRITE(1)TMPARA
  ENDDO
  IF( ICRCA3 == 1 )THEN
    WRITE(2,209)
    DO L=2,LA
      WRITE(2,200)L,IL(L),JL(L),(TEMLPF(L,K),K=1,KC)
    ENDDO
    WRITE(2,210)
  ENDIF
  CLOSE(1)
  IF( ICRCA3 == 1 ) CLOSE(2)
  !
  ! **  WRITE HYDROLOGY
  !
  OPEN(1,FILE=OUTDIR//'hydrlgy.inp',FORM='UNFORMATTED' &
        ,STATUS='UNKNOWN'  ,POSITION='APPEND')
  WRITE(1)TIMMID
  DO J=1,JC
    DO I=1,IC
      TMPARA(I,J)=0.
    ENDDO
  ENDDO
  DO L=2,LA
    TMPARA(IL(L),JL(L))=RAINLPF(L)
  ENDDO
  WRITE(1)TMPARA
  DO L=2,LA
    TMPARA(IL(L),JL(L))=EVPSLPF(L)
  ENDDO
  WRITE(1)TMPARA
  DO L=2,LA
    TMPARA(IL(L),JL(L))=RINFLPF(L)
  ENDDO
  WRITE(1)TMPARA
  CLOSE(1)
  IF( ICRCA3 == 1 )THEN
    OPEN(2,FILE=OUTDIR//'HYDRLGY.ASC',STATUS='UNKNOWN' &
         ,POSITION='APPEND')
    WRITE(2,106)TIME
    WRITE(2,212)
    DO L=2,LA
      WRITE(2,200)L,IL(L),JL(L),RAINLPF(L),EVPSLPF(L),EVPGLPF(L), &
          RINFLPF(L),GWLPF(L)
    ENDDO
    CLOSE(2)
  ENDIF
    200 FORMAT(3I5,6F15.6)
    201 FORMAT(' L,I(ROW),J(COL),QX(I,J,K),K=1,KC ',/)
    202 FORMAT(' L,I(ROW),J(COL),QY(I,J,K),K=1,KC ',/)
    203 FORMAT(' L,I(ROW),J(COL),QZ(I,J,K),K=1,KS ',/)
    204 FORMAT(' L,I(ROW),J(COL),AX(I,J,K),K=1,KC ',/)
    205 FORMAT(' L,I(ROW),J(COL),AY(I,J,K),K=1,KC ',/)
    206 FORMAT(' L,I(ROW),J(COL),AZ(I,J,K),K=1,KS ',/)
    207 FORMAT(' L,I(ROW),J(COL),SELS(I,J),SELE(I,J),DSEL(I,J) ',/)
    208 FORMAT(' L,I(ROW),J(COL),SAL(I,J,K),K=1,KC ',/)
    209 FORMAT(' L,I(ROW),J(COL),TEM(I,J,K),K=1,KC ',/)
    210 FORMAT(//)
    211 FORMAT(I5,2X,6E15.6)
    212 FORMAT(' L,I(ROW),J(ROW),RAINLPF(I,J),EVPSLPF(I,J),EVPGLPF(I,J), &
      RINFLPF(I,J),GWLPF(I,J) ',/)
    213 FORMAT(' NQINTFL,QINTFL ',/)
    215 FORMAT(' L,I(ROW),J(COL),SURFELV START AVG INTERVAL',/)
    216 FORMAT(' L,I(ROW),J(COL),DEL SURFELV OVER INTERVAL',/)
  RETURN
END

