SUBROUTINE RSALPLTH(ICON,CONC)

  ! **  SUBROUTINE RSALPLTH WRITES FILES FOR RESIDUAL SCALAR FIELD
  ! **  CONTOURING IN HORIZONTAL PLANES

  ! CHANGE RECORD

  USE GLOBAL
  IMPLICIT NONE
  INTEGER :: ICON,LINES,LEVELS,LEVELSS,LUN,L,LUNF,ITMP
  REAL :: CONC(LCM,KCM),DBS(10),TIME,TOXBT
  CHARACTER*80 TITLE
  !
  IF( JSRSPH(ICON) /= 1) GOTO 300
  LINES=LA-1
  LEVELS=2
  LEVELSS=3
  DBS(1)=0.
  DBS(2)=99.
  DBS(3)=-99.
  IF( ISTRAN(1) >= 1 )THEN
    TITLE='RESIDUAL HORIZONTAL SALINITY CONTOURS'
    LUN=11
    OPEN(LUN,FILE=OUTDIR//'RSALCNH.OUT',STATUS='UNKNOWN')
    CLOSE(LUN,STATUS='DELETE')
    OPEN(LUN,FILE=OUTDIR//'RSALCNH.OUT',STATUS='UNKNOWN')
    WRITE (LUN,99) TITLE
    WRITE (LUN,101)LINES,LEVELS
    WRITE (LUN,250)(DBS(L),L=1,LEVELS)
    CLOSE(LUN)
  ENDIF
  IF( ISTRAN(2) >= 1 )THEN
    TITLE='RESIDUAL HORIZONTAL TEMPERATURE CONTOURS'
    LUN=12
    OPEN(LUN,FILE=OUTDIR//'RTEMCNH.OUT',STATUS='UNKNOWN')
    CLOSE(LUN,STATUS='DELETE')
    OPEN(LUN,FILE=OUTDIR//'RTEMCNH.OUT',STATUS='UNKNOWN')
    WRITE (LUN,99) TITLE
    WRITE (LUN,101)LINES,LEVELS
    WRITE (LUN,250)(DBS(L),L=1,LEVELS)
    CLOSE(LUN)
  ENDIF
  IF( ISTRAN(3) >= 1 )THEN
    TITLE='RESIDUAL HORIZONTAL DYE CONC CONTOURS'
    LUN=13
    OPEN(LUN,FILE=OUTDIR//'RDYECNH.OUT',STATUS='UNKNOWN')
    CLOSE(LUN,STATUS='DELETE')
    OPEN(LUN,FILE=OUTDIR//'RDYECNH.OUT',STATUS='UNKNOWN')
    WRITE (LUN,99) TITLE
    WRITE (LUN,101)LINES,LEVELS
    WRITE (LUN,250)(DBS(L),L=1,LEVELS)
    CLOSE(LUN)
  ENDIF
  IF( ISTRAN(6) >= 1 )THEN
    TITLE='RESIDUAL HORIZ COHESIVE SEDIMENT CONC CONTOURS'
    LUN=14
    OPEN(LUN,FILE=OUTDIR//'RSEDCNH.OUT',STATUS='UNKNOWN')
    CLOSE(LUN,STATUS='DELETE')
    OPEN(LUN,FILE=OUTDIR//'RSEDCNH.OUT',STATUS='UNKNOWN')
    WRITE (LUN,99) TITLE
    WRITE (LUN,101)LINES,LEVELSS
    WRITE (LUN,250)(DBS(L),L=1,LEVELSS)
    CLOSE(LUN)
  ENDIF
  IF( ISTRAN(7) >= 1 )THEN
    TITLE='RESIDUAL HORIZ NONCOH SEDIMENT CONC CONTOURS'
    LUN=15
    OPEN(LUN,FILE=OUTDIR//'RSNDCNH.OUT',STATUS='UNKNOWN')
    CLOSE(LUN,STATUS='DELETE')
    OPEN(LUN,FILE=OUTDIR//'RSNDCNH.OUT',STATUS='UNKNOWN')
    WRITE (LUN,99) TITLE
    WRITE (LUN,101)LINES,LEVELSS
    WRITE (LUN,250)(DBS(L),L=1,LEVELSS)
    CLOSE(LUN)
  ENDIF
  IF( ISTRAN(5) >= 1 )THEN
    TITLE='RESIDUAL HORIZ TOXIC CONTAM CONC CONTOURS'
    LUN=16
    OPEN(LUN,FILE=OUTDIR//'RTOXCNH.OUT',STATUS='UNKNOWN')
    CLOSE(LUN,STATUS='DELETE')
    OPEN(LUN,FILE=OUTDIR//'RTOXCNH.OUT',STATUS='UNKNOWN')
    WRITE (LUN,99) TITLE
    WRITE (LUN,101)LINES,LEVELSS
    WRITE (LUN,250)(DBS(L),L=1,LEVELSS)
    CLOSE(LUN)
    TITLE='RESIDUAL HORIZ TOXIC PART FRAC CONTOURS'
    LUNF=26
    OPEN(LUNF,FILE=OUTDIR//'RTXPCNH.OUT',STATUS='UNKNOWN')
    CLOSE(LUNF,STATUS='DELETE')
    OPEN(LUNF,FILE=OUTDIR//'RTXPCNH.OUT',STATUS='UNKNOWN')
    WRITE (LUNF,99) TITLE
    WRITE (LUNF,101)LINES,LEVELSS
    WRITE (LUNF,250)(DBS(L),L=1,LEVELSS)
    CLOSE(LUNF)
  ENDIF
  IF( ISTRAN(4) >= 1 )THEN
    TITLE='RESIDUAL HORIZONTAL SFL CONC CONTOURS'
    LUN=17
    OPEN(LUN,FILE=OUTDIR//'RSFLCNH.OUT',STATUS='UNKNOWN')
    CLOSE(LUN,STATUS='DELETE')
    OPEN(LUN,FILE=OUTDIR//'RSFLCNH.OUT',STATUS='UNKNOWN')
    WRITE (LUN,99) TITLE
    WRITE (LUN,101)LINES,LEVELSS
    WRITE (LUN,250)(DBS(L),L=1,LEVELSS)
    CLOSE(LUN)
  ENDIF
  DO ITMP=1,7
    JSRSPH(ITMP)=0
  ENDDO
    300 CONTINUE
  IF( ICON == 1 )THEN
    LUN=11
    OPEN(LUN,FILE=OUTDIR//'RSALCNH.OUT',POSITION='APPEND' &
            ,STATUS='UNKNOWN')
  ENDIF
  IF( ICON == 2 )THEN
    LUN=12
    OPEN(LUN,FILE=OUTDIR//'RTEMCNH.OUT',POSITION='APPEND' &
            ,STATUS='UNKNOWN')
  ENDIF
  IF( ICON == 3 )THEN
    LUN=13
    OPEN(LUN,FILE=OUTDIR//'RDYECNH.OUT',POSITION='APPEND' &
            ,STATUS='UNKNOWN')
  ENDIF
  IF( ICON == 6 )THEN
    LUN=14
    OPEN(LUN,FILE=OUTDIR//'RSEDCNH.OUT',POSITION='APPEND' &
            ,STATUS='UNKNOWN')
  ENDIF
  IF( ICON == 7 )THEN
    LUN=15
    OPEN(LUN,FILE=OUTDIR//'RSNDCNH.OUT',POSITION='APPEND' &
            ,STATUS='UNKNOWN')
  ENDIF
  IF( ICON == 5 )THEN
    LUN=16
    OPEN(LUN,FILE=OUTDIR//'RTOXCNH.OUT',POSITION='APPEND' &
            ,STATUS='UNKNOWN')
    LUNF=26
    OPEN(LUNF,FILE=OUTDIR//'RTXPCNH.OUT', &
        POSITION='APPEND',STATUS='UNKNOWN')
  ENDIF
  IF( ICON == 4 )THEN
    LUN=17
    OPEN(LUN,FILE=OUTDIR//'RSFLCNH.OUT',POSITION='APPEND' &
            ,STATUS='UNKNOWN')
  ENDIF
  IF( ISDYNSTP == 0 )THEN
    TIME=DT*FLOAT(N)+TCON*TBEGIN
    TIME=TIME/TCON
  ELSE
    TIME=TIMESEC/TCON
  ENDIF
  WRITE (LUN,100)N,TIME
  IF( ICON == 5 )THEN
    WRITE (LUNF,100)N,TIME
  ENDIF
  IF( ISPHXY(ICON) == 0 )THEN
    IF( ICON <= 3 )THEN
      DO L=2,LA
        WRITE(LUN,400)CONC(L,KC),CONC(L,KSZ(L))
      ENDDO
    ENDIF
    IF( ICON >= 8 )THEN
      DO L=2,LA
        WRITE(LUN,400)CONC(L,KC),CONC(L,KSZ(L))
      ENDDO
    ENDIF
    IF( ICON == 6 )THEN
      DO L=2,LA
  !
  !      SEDBT=1000*SSG*SEDB(L)
  !
        WRITE(LUN,400)CONC(L,KC),CONC(L,KSZ(L)), &
            SEDBTLPF(L,KBT(L))
      ENDDO
    ENDIF
    IF( ICON == 7 )THEN
      DO L=2,LA
  !
  !      SEDBT=1000*SSG*SNDB(L,KBT(L))
  !
        WRITE(LUN,400)CONC(L,KC),CONC(L,KSZ(L)), &
            SNDBTLPF(L,KBT(L))
      ENDDO
    ENDIF
    IF( ICON == 5 )THEN
      DO L=2,LA
        TOXBT=1000.*TOXBLPF(L,KBT(L),1)
        WRITE(LUN,400)CONC(L,KC),CONC(L,KSZ(L)), &
            TOXBT
      ENDDO
      DO L=2,LA
  !
  !      SEDBT=1000*SSG*SEDB(L,KBT(L),1)
  !
        WRITE(LUNF,400)TXPFLPF(L,KC,1,1), &
            TXPFLPF(L,1,1,1),TOXBLPF(L,KBT(L),1)
      ENDDO
      CLOSE(LUNF)
    ENDIF
    IF( ICON == 4 )THEN
      DO L=2,LA
        WRITE(LUN,400)CONC(L,KC),CONC(L,KSZ(L)), &
            SFLSBOT(L)
      ENDDO
    ENDIF
  ENDIF
  IF( ISPHXY(ICON) == 1 )THEN
    IF( ICON <= 3 )THEN
      DO L=2,LA
        WRITE(LUN,200)IL(L),JL(L),CONC(L,KC),CONC(L,KSZ(L))
      ENDDO
    ENDIF
    IF( ICON >= 8 )THEN
      DO L=2,LA
        WRITE(LUN,200)IL(L),JL(L),CONC(L,KC),CONC(L,KSZ(L))
      ENDDO
    ENDIF
    IF( ICON == 6 )THEN
      DO L=2,LA
  !
  !      SEDBT=1000*SSG*SEDB(L)
  !
        WRITE(LUN,200)IL(L),JL(L),CONC(L,KC),CONC(L,KSZ(L)), &
            SEDBTLPF(L,KBT(L))
      ENDDO
    ENDIF
    IF( ICON == 7 )THEN
      DO L=2,LA
  !
  !      SEDBT=1000*SSG*SNDB(L,KBT(L))
  !
        WRITE(LUN,200)IL(L),JL(L),CONC(L,KC),CONC(L,KSZ(L)), &
            SNDBTLPF(L,KBT(L))
      ENDDO
    ENDIF
    IF( ICON == 5 )THEN
      DO L=2,LA
        TOXBT=1000.*TOXBLPF(L,KBT(L),1)
        WRITE(LUN,200)IL(L),JL(L),CONC(L,KC),CONC(L,KSZ(L)), &
            TOXBT
      ENDDO
      DO L=2,LA
  !
  !      SEDBT=1000*SSG*SEDB(L,KBT(L),1)
  !
        WRITE(LUNF,200)IL(L),JL(L),TXPFLPF(L,KC,1,1), &
            TXPFLPF(L,1,1,1),TOXBLPF(L,KBT(L),1)
      ENDDO
      CLOSE(LUNF)
    ENDIF
    IF( ICON == 4 )THEN
      DO L=2,LA
        WRITE(LUN,200)IL(L),JL(L),CONC(L,KC),CONC(L,KSZ(L)), &
            SFLSBOT(L)
      ENDDO
    ENDIF
  ENDIF
  IF( ISPHXY(ICON) == 2 )THEN
    IF( ICON <= 3 )THEN
      DO L=2,LA
      WRITE(LUN,200)IL(L),JL(L),DLON(L),DLAT(L),CONC(L,KC),CONC(L,KSZ(L))
      ENDDO
    ENDIF
    IF( ICON >= 8 )THEN
      DO L=2,LA
      WRITE(LUN,200)IL(L),JL(L),DLON(L),DLAT(L),CONC(L,KC),CONC(L,KSZ(L))
      ENDDO
    ENDIF
    IF( ICON == 6 )THEN
      DO L=2,LA
  !
  !      SEDBT=1000*SSG*SEDB(L)
  !
        WRITE(LUN,200)IL(L),JL(L),DLON(L),DLAT(L),CONC(L,KC), &
                 CONC(L,KSZ(L)),SEDBTLPF(L,KBT(L))
      ENDDO
    ENDIF
    IF( ICON == 7 )THEN
      DO L=2,LA
  !
  !      SEDBT=1000*SSG*SNDB(L,KBT(L))
  !
        WRITE(LUN,200)IL(L),JL(L),DLON(L),DLAT(L),CONC(L,KC), &
                 CONC(L,KSZ(L)),SNDBTLPF(L,KBT(L))
      ENDDO
    ENDIF
    IF( ICON == 5 )THEN
      DO L=2,LA
        TOXBT=1000.*TOXBLPF(L,KBT(L),1)
        WRITE(LUN,200)IL(L),JL(L),DLON(L),DLAT(L),CONC(L,KC), &
                 CONC(L,KSZ(L)),TOXBT
      ENDDO
      DO L=2,LA
  !
  !      SEDBT=1000*SSG*SEDB(L,KBT(L),1)
  !
       WRITE(LUNF,200)IL(L),JL(L),DLON(L),DLAT(L),TXPFLPF(L,KC,1,1), &
            TXPFLPF(L,1,1,1),TOXBLPF(L,KBT(L),1)
      ENDDO
      CLOSE(LUNF)
    ENDIF
    IF( ICON == 4 )THEN
      DO L=2,LA
        WRITE(LUN,200)IL(L),JL(L),DLON(L),DLAT(L),CONC(L,KC), &
                 CONC(L,KSZ(L)),SFLSBOT(L)
      ENDDO
    ENDIF
  ENDIF
  CLOSE(LUN)
     99 FORMAT(A80)
    100 FORMAT(I10,F12.4)
    101 FORMAT(2I10)
    200 FORMAT(2I5,1X,6E14.6)
    250 FORMAT(12E12.4)
    400 FORMAT(1X,6E14.6)
    420 FORMAT(1X,13E11.3)
  RETURN
END

