SUBROUTINE SETOPENBC2

  ! CHANGE RECORD
  ! ** SUBROUTINE SETOBC SETS OPEN BOUNDARY CONDITIONS FOR
  !    CALPUV2T & CALPUV2C   AND  CALPUV9 & CALPUV9C
  !
  ! *** MODIFIED BY PAUL M. CRAIG

  USE GLOBAL
  IMPLICIT NONE
  
  INTEGER :: LL,L,LS,LN
  
  ! *** SET OPEN BOUNDARY SURFACE ELEVATIONS FOR ADJACENT CELLS,
  ! *** IF NOT RADIATION SEPARATION SPECIFIED

  DO LL=1,NPBW
    IF( ISPBW(LL) == 0 )THEN
      L=LPBW(LL)
      CW(LEC(L))=0.
    ENDIF
  ENDDO

  DO LL=1,NPBE
    IF( ISPBE(LL) == 0 )THEN
      L=LPBE(LL)
      CE(LWC(L))=0.
    ENDIF
  ENDDO

  DO LL=1,NPBS
    IF( ISPBS(LL) == 0 )THEN
      L=LPBS(LL)
      LN=LNC(L)
      CS(LN)=0.
    ENDIF
  ENDDO

  DO LL=1,NPBN
    IF( ISPBN(LL) == 0 )THEN
      L=LPBN(LL)
      LS=LSC(L)
      CN(LS)=0.
    ENDIF
  ENDDO

  RETURN
END
