SUBROUTINE WQ3DINP
  
  !  READ WATER QUALITY SUBMODEL INPUT FILES
  !  ORGINALLY CODED BY K.-Y. PARK
  !  OPTIMIZED AND MODIFIED BY J. M. HAMRICK
  
  ! CHANGE RECORD
  
  USE GLOBAL
  USE WQ_RPEM_MODULE
  USE RESTART_MODULE

  IMPLICIT NONE

  INTEGER :: J,L,K,IWQTICI,IWQTAGR,IWQTSTL,IWQTSUN,IWQTBEN,IWQTPSL,IWQTNPL,ISMTICI,NWQVOUT,NW

  CHARACTER*3 CWQHDR(NWQVM)
  DATA IWQTICI,IWQTAGR,IWQTSTL,IWQTSUN,IWQTBEN,IWQTPSL,IWQTNPL/7*0/
  DATA ISMTICI/0/

  IWQTICI=IWQTICI
  IWQTAGR=IWQTAGR
  IWQTSTL=IWQTSTL
  IWQTSUN=IWQTSUN
  IWQTBEN=IWQTBEN
  IWQTPSL=IWQTPSL
  IWQTNPL=IWQTNPL
  ISMTICI=ISMTICI
  OPEN(1,FILE=OUTDIR//'WQ3D.OUT',STATUS='UNKNOWN')
  CLOSE(1,STATUS='DELETE')
  !
  ! **  HARDWIRE BY PASS OF RATE COEFFICIENT MAPS
  !
  WQKCNT=0.
  WQKINUPT=DT/86400.  ! WQ VARIABLE DT
  UHEQ(1)=0.0
  UHEQ(LC)=0.0
  DO L=2,LA
    UHEQ(L)=1.0
  ENDDO
  ITNWQ = 0
  ! *** Fractional of Depth at the Top of the Layer
  RKCWQ = 1.0/REAL(KC)
  DO K=1,KC
    WQHT(K)=REAL(KC-K)*RKCWQ
  ENDDO
  !
  WQTSNAME(1)  = 'CHC'
  WQTSNAME(2)  = 'CHD'
  WQTSNAME(3)  = 'CHG'
  WQTSNAME(4)  = 'ROC'
  WQTSNAME(5)  = 'LOC'
  WQTSNAME(6)  = 'DOC'
  WQTSNAME(7)  = 'ROP'
  WQTSNAME(8)  = 'LOP'
  WQTSNAME(9)  = 'DOP'
  WQTSNAME(10) = 'P4D'
  WQTSNAME(11) = 'RON'
  WQTSNAME(12) = 'LON'
  WQTSNAME(13) = 'DON'
  WQTSNAME(14) = 'NHX'
  WQTSNAME(15) = 'NOX'
  WQTSNAME(16) = 'SUU'
  WQTSNAME(17) = 'SAA'
  WQTSNAME(18) = 'COD'
  WQTSNAME(19) = 'DOX'
  WQTSNAME(20) = 'TAM'
  WQTSNAME(21) = 'FCB'
  IF( NWQV > 21 )THEN
    WQTSNAME(22) = 'CO2'
    WQTSNAME(23) = 'MAC'
  ELSE
    WQTSNAME(22) = 'MAC'
  ENDIF
  !      DO M=0,NWQPS
  !        WQPSQ(M)=0.0   ! *** PMC-NOT USED
  !        WQPSQC(M)=0.0  ! *** PMC-NOT USED
  !        DO J=1,NWQV
  !          WQWPSLC(M,J)=0.0
  !        ENDDO
  !      ENDDO
  DO K=1,KC
    IWQPSC(1,K)=0
  !        WQDSQ(1,K)=0.0
    IWQPSC(LC,K)=0
  !        WQDSQ(LC,K)=0.0
  ENDDO
  DO K=1,KC
    DO L=2,LA
      IWQPSC(L,K)=0
      IWQPSV(L,K)=0
  !            WQDSQ(L,K)=0.0
    ENDDO
  ENDDO
  DO J=1,NWQV
    DO K=1,KC
      DO L=1,LC
        WQWDSL(L,K,J)=0.0
        WQWPSL(L,K,J)=0.0
      ENDDO
    ENDDO
  ENDDO
  CALL WQ3DCONTROL

  !      CALL RWQC2
  !      CALL RWQMAP

  OPEN(1,FILE=OUTDIR//'WQWCTS.OUT',STATUS='UNKNOWN')
  CLOSE(1,STATUS='DELETE')
  OPEN(1,FILE=OUTDIR//'WQWCTS.OUT',STATUS='UNKNOWN')
  NWQVOUT=0
  DO NW=1,NWQV
    IF( ISTRWQ(NW) == 1 )THEN
      NWQVOUT=NWQVOUT+1
      CWQHDR(NWQVOUT)=WQTSNAME(NW)
    ENDIF
  ENDDO
  WRITE(1,1969)(CWQHDR(NW),NW=1,NWQVOUT)
   1969 FORMAT('C   I    J    K    TIME',7X,A3,8X,A3,8X,A3, &
      8X,A3,8X,A3,8X,A3,8X,A3,8X,A3,8X,A3, &
      8X,A3,8X,A3,8X,A3,8X,A3,8X,A3,8X,A3, &
      8X,A3,8X,A3,8X,A3,8X,A3,8X,A3,8X,A3)
  CLOSE(1)

  ! **  INITIALIZE DIURNAL DO ANALYSIS
  IF( NDDOAVG >= 1 .AND. DEBUG )THEN
    OPEN(1,FILE=OUTDIR//'DIURNDO.OUT')
    CLOSE(1,STATUS='DELETE')
    DO K=1,KC
      DO L=2,LA
        DDOMAX(L,K)=-1.E6
        DDOMIN(L,K)=1.E6
      ENDDO
    ENDDO
  ENDIF

  ! **  INITIALIZE LIGHT EXTINCTION ANALYSIS
  IF( NDLTAVG >= 1 )THEN
    OPEN(1,FILE=OUTDIR//'LIGHT.OUT')
    CLOSE(1,STATUS='DELETE')
    NDLTCNT=0
    DO K=1,KC
      DO L=2,LA
        RLIGHTT(L,K)=0.
        RLIGHTC(L,K)=0.
      ENDDO
    ENDDO
  ENDIF

  ! *** SEDIMENT DIAGENESIS
  IF( IWQBEN == 1 )THEN
    DO L=2,LA
      SMHYST(L)=.FALSE.
    ENDDO

    CALL SMRIN1
    IF( ISMICI == 2 ) CALL RSMRST
  ENDIF

  ! *** RPEM
  IF( ISRPEM > 0 )THEN
    CALL INIT_RPEMVARS
    CALL RPEMINP
  ENDIF

  ! *** READ WQ TIMESERIES
  IF( IWQPSL/=0)CALL WQCSR !SCJ skip reading WQCSR if there are onl!y constant point source loads
  !
    100 FORMAT('  TIME = ',A11,' HH.MM.SS.HH')
  RETURN
END

