SUBROUTINE WQBENTHIC (TIMTMP)

  ! *** RWQBEN2

  ! READ IN SPATIALLY AND/OR TEMPORALLY VARYING PARAMETERS FOR BENTHIC
  ! FLUXES OF PO4D, NH4, NO3, SAD, COD, O2
  ! FORMAT OF BENFN FILE IS:
  !    TITLE 1
  !    TITLE 2
  !    TITLE 3
  !  270.00000  <-- DAY AT WHICH FOLLOWING FLUXES BECOME ACTIVE
  !  350.00000  <-- DAY AT WHICH FOLLOWING FLUXES BECOME ACTIVE
  ! 9999.99999 <-- ENTER LARGE DAY AT END OF FILE

  USE GLOBAL
  USE INFOMOD,ONLY:SKIPCOM
  IMPLICIT NONE
  
  REAL,INTENT(IN) :: TIMTMP
  INTEGER :: M,MM,IBENZ,I,L,IZM,IZS
  REAL    :: XBSFAD,BDAY,XM
  
  CHARACTER TITLE(3)*79, CCMRM*1
  INTEGER,SAVE,ALLOCATABLE,DIMENSION(:) :: IZONE
  REAL,SAVE,ALLOCATABLE,DIMENSION(:) :: XBFCOD
  REAL,SAVE,ALLOCATABLE,DIMENSION(:) :: XBFNH4
  REAL,SAVE,ALLOCATABLE,DIMENSION(:) :: XBFNO3
  REAL,SAVE,ALLOCATABLE,DIMENSION(:) :: XBFO2
  REAL,SAVE,ALLOCATABLE,DIMENSION(:) :: XBFPO4D
  REAL,SAVE,ALLOCATABLE,DIMENSION(:) :: XBFSAD

  IF(  .NOT. ALLOCATED(IZONE  ) )THEN
    ALLOCATE(IZONE(NSMZM))
    ALLOCATE(XBFCOD(NSMZM))
    ALLOCATE(XBFNH4(NSMZM))
    ALLOCATE(XBFNO3(NSMZM))
    ALLOCATE(XBFO2(NSMZM))
    ALLOCATE(XBFPO4D(NSMZM))
    ALLOCATE(XBFSAD(NSMZM))
    IZONE=0
    XBFCOD=0.0
    XBFNH4=0.0
    XBFNO3=0.0
    XBFO2=0.0
    XBFPO4D=0.0
    XBSFAD=0.0
  ENDIF

  WRITE(*,'(A)')' WQ: '//BENFN
  OPEN(1,FILE=BENFN,STATUS='UNKNOWN')
  OPEN(2,FILE=OUTDIR//'WQ3D.OUT',STATUS='UNKNOWN',POSITION='APPEND')

  ! SKIP OVER THREE HEADER RECORDS:
  READ(1,50) (TITLE(M),M=1,3)
  WRITE(2,999)
  WRITE(2,50) (TITLE(M),M=1,3)

  ! SKIP OVER ALL COMMENT CARDS AT BEGINNING OF FILE:
  REWIND(1)
  CCMRM = '#'
  CALL SKIPCOM(1, CCMRM,2)
  READ(1, *) IBENZ
  WRITE(2, 65) TIMTMP, IBENZ
  65 FORMAT(' * BENTHIC FLUXES AT     ', F10.5,' DAYS OF MODEL RUN',/, & 
            '   NUMBER OF BENTHIC FLUX ZONES = ', I4)

  ! SEQUENTIALLY READ THROUGH BENTHIC FLUX FILE UNTIL THE APPROPRIATE
  ! TIME IS FOUND:
  !   BDAY   = CURRENT DAY AT WHICH BENTHIC FLUX IS IN EFFECT
  !   BENDAY = NEXT DAY AT WHICH BENTHIC FLUX CHANGES (PASSED TO MAIN PROG

  10 READ(1, *, END=15) BENDAY

  IF( BENDAY  >  TIMTMP) GOTO 20
  BDAY = BENDAY
  DO I=1,IBENZ
    READ(1,*,END=15) MM, XBFPO4D(MM), XBFNH4(MM), XBFNO3(MM),XBFSAD(MM), XBFCOD(MM), XBFO2(MM)
    IZONE(I) = MM
  ENDDO
  GOTO 10

  ! UNEXPECTED END-OF-FILE ENCOUNTERED:
  15 WRITE(2,16) BENFN
  16 FORMAT(//,' ************* WARNING *************',/, &
               ' END-OF-FILE ENCOUNTERED IN FILE: ', A20,/,/ &
               ' BENTHIC FLUXES SET TO VALUES CORRESPONDING TO LAST DAY IN FILE.',/)
  BENDAY=(TCON*TBEGIN + NTC*TIDALP)/86400.0  ! *** PMC SINGLE LINE

  20 CONTINUE
  WRITE(2, 48) BDAY
  48 FORMAT(/,' DAY IN BENTHIC FLUX FILE: ',F10.5,/, &
              '    ZONE    FPO4    FNH4    FNO3    FSAD    FCOD    FSOD')
  DO I=1,IBENZ
    MM = IZONE(I)
    WRITE(2,51) MM,XBFPO4D(MM),XBFNH4(MM),XBFNO3(MM),XBFSAD(MM),XBFCOD(MM),XBFO2(MM)
  ENDDO

  ! DETERMINE BENTHIC FLUX FOR EACH CELL (L) BY INTERPOLATING BETWEEN
  ! THE MUD AND SAND FLUXES.  XBENMUD(L) IS THE PERCENT MUD FOR EACH CELL.
  DO L=2,LA
    IZM = IBENMAP(L,1)
    IZS = IBENMAP(L,2)
    XM = XBENMUD(L)
    WQBFPO4D(L) = XM*XBFPO4D(IZM) + (1.0-XM)*XBFPO4D(IZS)
    WQBFNH4(L)  = XM*XBFNH4(IZM)  + (1.0-XM)*XBFNH4(IZS)
    WQBFNO3(L)  = XM*XBFNO3(IZM)  + (1.0-XM)*XBFNO3(IZS)
    WQBFSAD(L)  = XM*XBFSAD(IZM)  + (1.0-XM)*XBFSAD(IZS)
    WQBFCOD(L)  = XM*XBFCOD(IZM)  + (1.0-XM)*XBFCOD(IZS)
    WQBFO2(L)   = XM*XBFO2(IZM)   + (1.0-XM)*XBFO2(IZS)
  ENDDO
  
  CLOSE(1)
  CLOSE(2)
  
  999 FORMAT(1X)
   50 FORMAT(A79)
   51 FORMAT(I8, 10F8.3)
   52 FORMAT(I7, 1X, A3)
   60 FORMAT(/, A24, I5, A24)

  RETURN

END

