SUBROUTINE WQCSR

  ! *** RWQCSR

  ! CHANGE RECORD

  USE GLOBAL

  IMPLICIT NONE

  CHARACTER*11 FNWQSR(40)
  CHARACTER*2  SNUM
  INTEGER NT,NW,IS,NS,ISO,ISTYP,K,M
  REAL    RMULADJ,ADDADJ,CSERTMP

  WRITE(*,'(A)') ' WQ: READING CWQSRxx.INP - WQ CONCENTRATION TIME SERIES'

  ! *** DEFINE THE INPUT FILE NAMES
  DO NW = 1,NWQV
    WRITE(SNUM,'(I2.2)')NW
    FNWQSR(NW)='cwqsr'//SNUM//'.inp'
  ENDDO
  !
  ! **  READ IN OPEN BOUNDARY OR VOLUMETRIC SOURCE WQ CONCENTRATION
  ! **  TIME SERIES FROM THE FILES CWQSRNN.INP
  !
  DO NW=1,NWQV
    IF( NWQCSR(NW) >= 1 )THEN
      OPEN(1,FILE=FNWQSR(NW),STATUS='UNKNOWN')
  
      ! **  SKIP OVER TITLE AND AND HEADER LINES
      DO IS=1,15
        READ(1,1)
      ENDDO

      NT=4+NTOX+NSED+NSND+NW
      DO NS=1,NWQCSR(NW)
        MCTLAST(NS,NT)=2
        READ(1,*,IOSTAT=ISO)ISTYP,MCSER(NS,NT),TCCSER(NS,NT),TACSER(NS,NT),RMULADJ,ADDADJ
        IF( ISO > 0 ) GOTO 900
        IF( ISTYP == 1 )THEN
          READ(1,*,IOSTAT=ISO) (WKQ(K),K=1,KC)
          IF( ISO > 0 ) GOTO 900
          DO M=1,MCSER(NS,NT)
            READ(1,*,IOSTAT=ISO) TSWQ(NS,NW).TIM(M),CSERTMP
            IF( ISO > 0 ) GOTO 900
            TSWQ(NS,NW).TIM(M) = TSWQ(NS,NW).TIM(M) + TACSER(NS,NT)
            DO K=1,KC
              TSWQ(NS,NW).VAL(M,K) = ( RMULADJ*(CSERTMP + ADDADJ) )*WKQ(K)
            ENDDO
          ENDDO
        ELSE
          DO M=1,MCSER(NS,NT)
            READ(1,*,IOSTAT=ISO) TSWQ(NS,NW).TIM(M),(TSWQ(NS,NW).VAL(M,K), K=1,KC)
            IF( ISO > 0 ) GOTO 900
            TSWQ(NS,NW).TIM(M)=TSWQ(NS,NW).TIM(M)+TACSER(NS,NT)
            DO K=1,KC
              TSWQ(NS,NW).VAL(M,K) = RMULADJ*( TSWQ(NS,NW).VAL(M,K) + ADDADJ )
            ENDDO
          ENDDO
        ENDIF
      ENDDO
      CLOSE(1)
    ENDIF
  ENDDO

  GOTO 901

  900 CONTINUE
  WRITE(6,601)NW,NS,M
  STOP

  901 CONTINUE
    1 FORMAT(120X)
  601 FORMAT(' READ ERROR WQ TIME SERIES, NWQ,NSER,MDATA = ',3I5)
  602 FORMAT(' READ OF FILES CWQSRNN.INP SUCCESSFUL'/)

  RETURN

END

