SUBROUTINE WQSUN

  ! *** RWQSUN
  ! READ IN TEMPORALLY VARYING PARAMETERS FOR DAILY SOLAR RADIATION (WQI0)
  ! AND FRACTIONAL DAYLENGTH (WQFD) (UNIT INWQSUN).
  !
  !
  ! **  NEW VERSION BY J. M. HAMRICK  7 APRIL 1997
  ! CHANGE RECORD
  ! **  READS AND INTERPOLATES DAILY AVERAGE SOLAR RADIATION AND
  ! **  DAYLIGHT FRACTION
  !
  USE GLOBAL

  INTEGER :: IS,M,ISO,NSUNDAY,M1,M2
  REAL    :: TCSUNDAY,TASUNDAY,RMULADJ,ADDADJ,TDIFF,WTM1,WTM2,TIME

  IF( ITNWQ > 0 ) GOTO 1000
  !
  ! **  READ IN DAILY AVERAGE SOLAR SW RAD SERIES FROM FILE 'SUNDAY.INP'
  !
  WRITE(*,'(A)')' WQ: SUNDAY.INP'
  OPEN(1,FILE='sunday.inp',STATUS='UNKNOWN')
  !
  ! **  SKIP OVER TITLE AND AND HEADER LINES
  !
  DO IS=1,7
    READ(1,1)
  ENDDO
  M=0
  ISPAR=1
  !
  !      MCSUNDAY=1 TEMP USE ISPAR FOR MCSUNDAY
  !
  READ(1,*,IOSTAT=ISO)NSUNDAY,TCSUNDAY,TASUNDAY,RMULADJ,ADDADJ
  IF( ISO > 0 ) GOTO 900
  DO M=1,NSUNDAY
    READ(1,*,IOSTAT=ISO)TSSRD(M),SOLSRD(M),SOLFRD(M)
    IF( ISO > 0 ) GOTO 900
    TSSRD(M)=TCSUNDAY*( TSSRD(M)+TASUNDAY )
    SOLSRD(M)=RMULADJ*(SOLSRD(M)+ADDADJ) * PARADJ
  ENDDO
  CLOSE(1)
  GOTO 901
    900 CONTINUE
  WRITE(6,601)M
  STOP
    901 CONTINUE
      1 FORMAT(120X)
601     FORMAT(' READ ERROR FILE SUNDAY.INP ')
        
   1000 CONTINUE
  !
  ! **  DAILY AVERAGE SOLAR SW RADIATION INTERPOLTATION FOR WATER QUALITY
  !
  IF( ISDYNSTP == 0 )THEN
    TIME=(DT*FLOAT(N)+TCON*TBEGIN)/86400.
  ELSE
    TIME=TIMESEC/86400.
  ENDIF
  M1=ISPAR
  !
  !      TEMP USE ISPAR FOR MCSUNDAY
  !
    100 CONTINUE
  M2=M1+1
  IF( TIME > TSSRD(M2) )THEN
    M1=M2
    GOTO 100
  ELSE
    ISPAR=M1
  !
  !      TEMP USE ISPAR FOR MCSUNDAY
  !
  ENDIF
  TDIFF=TSSRD(M2)-TSSRD(M1)
  WTM1=(TSSRD(M2)-TIME)/TDIFF
  WTM2=(TIME-TSSRD(M1))/TDIFF
  SOLSRDT=WTM1*SOLSRD(M1)+WTM2*SOLSRD(M2)
  SOLFRDT=WTM1*SOLFRD(M1)+WTM2*SOLFRD(M2)
  RETURN
END

